import {
  defineLineFromSegments as line,
  definePly as ply,
  defineQuizQuestion as quiz,
} from "./schema.js";

const VIENNA_START = [
  ply("e2", "e4", "e4", "White claims central space and opens the queen and light-squared bishop."),
  ply("e7", "e5", "e5", "Black matches White in the center and releases both kingside pieces."),
  ply("b1", "c3", "Nc3", "The knight supports e4 while keeping the f-pawn free for an attacking advance."),
];

const KINGS_GAMBIT_START = [
  ply("e2", "e4", "e4", "White takes central space and opens lines for fast development."),
  ply("e7", "e5", "e5", "Black builds an equal central foothold and frees the kingside."),
  ply("f2", "f4", "f4", "White offers the f-pawn to deflect e5 and gain open attacking lines."),
];

const SCANDINAVIAN_START = [
  ply("e2", "e4", "e4", "White occupies the center and frees the bishop and queen."),
  ply("d7", "d5", "d5", "Black challenges e4 immediately, forcing an early central decision."),
  ply("e4", "d5", "exd5", "White accepts the challenge and removes Black's central pawn."),
];

const PIRC_START = [
  ply("e2", "e4", "e4", "White claims central space and opens two lines for development."),
  ply("d7", "d6", "d6", "Black restrains e5 and keeps the central pawn structure flexible."),
  ply("d2", "d4", "d4", "White forms a broad pawn center before Black directly contests it."),
  ply("g8", "f6", "Nf6", "The knight attacks e4 and invites White to reveal how the center will be defended."),
  ply("b1", "c3", "Nc3", "White protects e4 and adds another piece to the central fight."),
  ply("g7", "g6", "g6", "Black prepares a fianchetto that will pressure the center from the long diagonal."),
];

const ALEKHINE_START = [
  ply("e2", "e4", "e4", "White occupies the center and opens natural development."),
  ply("g8", "f6", "Nf6", "Black attacks e4 at once, inviting the pawn forward so it can later become a target."),
  ply("e4", "e5", "e5", "White gains space and drives the knight, accepting Black's strategic challenge."),
  ply("f6", "d5", "Nd5", "The knight chooses a central retreat that keeps pressure on c3 and e3."),
];

const NIMZO_START = [
  ply("d2", "d4", "d4", "White claims central space and opens the dark-squared bishop."),
  ply("g8", "f6", "Nf6", "Black controls e4 without committing a central pawn."),
  ply("c2", "c4", "c4", "White challenges d5 and builds the classical queen's-pawn center."),
  ply("e7", "e6", "e6", "Black opens the f8 bishop and prepares to contest the center with ...d5 or ...c5."),
  ply("b1", "c3", "Nc3", "White reinforces d5 and increases the possibility of e4."),
  ply("f8", "b4", "Bb4", "Black pins the c3 knight, restraining e4 and threatening structural damage."),
];

const GRUNFELD_START = [
  ply("d2", "d4", "d4", "White takes central space and frees the c1 bishop."),
  ply("g8", "f6", "Nf6", "Black controls e4 and waits before fixing the center."),
  ply("c2", "c4", "c4", "White strengthens the center and challenges d5."),
  ply("g7", "g6", "g6", "Black prepares a kingside fianchetto and long-range pressure."),
  ply("b1", "c3", "Nc3", "White supports d5 and makes e4 possible."),
  ply("d7", "d5", "d5", "Black strikes at once, inviting White to build a large center that can be attacked."),
];

const DUTCH_START = [
  ply("d2", "d4", "d4", "White claims central space and releases the c1 bishop."),
  ply("f7", "f5", "f5", "Black controls e4 and accepts kingside risk for an unbalanced attacking game."),
];

const LONDON_START = [
  ply("d2", "d4", "d4", "White secures central space and opens the dark-squared bishop."),
  ply("d7", "d5", "d5", "Black establishes an equal central foothold."),
  ply("g1", "f3", "Nf3", "White develops, controls e5, and keeps several move orders available."),
  ply("g8", "f6", "Nf6", "Black develops naturally and adds pressure to e4 and d5."),
  ply("c1", "f4", "Bf4", "The London bishop reaches its active post before e3 closes its diagonal."),
];

const CATALAN_START = [
  ply("d2", "d4", "d4", "White claims central space and opens the c1 bishop."),
  ply("g8", "f6", "Nf6", "Black controls e4 while keeping the central pawn choice flexible."),
  ply("c2", "c4", "c4", "White increases pressure on d5 and builds a queen's-pawn center."),
  ply("e7", "e6", "e6", "Black opens the dark-squared bishop and prepares ...d5 or ...Bb4+."),
  ply("g2", "g3", "g3", "White prepares the Catalan fianchetto, aiming the bishop at the queenside."),
];

export const ADDITIONAL_OPENINGS = [
  {
    id: "vienna",
    name: "Vienna Game",
    side: "White",
    difficulty: "Beginner",
    style: ["Tactical", "Flexible", "Beginner Friendly"],
    startingMoves: "1.e4 e5 2.Nc3",
    character: "Flexible development with sudden kingside attacks",
    skillLevel: "Beginner to intermediate",
    glyph: "♘",
    intro: "The Vienna develops the queen's knight before Nf3, preserving the option of f4. White can play quietly or launch a genuine gambit, so the opening teaches how development, central pressure, and king safety support an attack.",
    objectives: [
      "Support e4 without blocking the f-pawn",
      "Choose between quiet development and the f4 gambit",
      "Develop the kingside before opening more lines",
      "Use pressure on e5 to gain time",
      "Recognize when Black's central counterstrike ...d5 is sound",
    ],
    plans: {
      white: [
        "Play f4 when development can support the opened f-file.",
        "Use Bc4 to increase pressure on f7.",
        "Build with d3 or strike with d4 according to Black's setup.",
        "Castle before turning space into a direct attack.",
      ],
      black: [
        "Meet f4 with the central break ...d5 when possible.",
        "Develop ...Nf6 and pressure e4 immediately.",
        "Use ...Bb4 to pin Nc3 and increase central control.",
        "Avoid pawn grabbing when the king is still exposed.",
      ],
    },
    keySquares: [
      { square: "e5", label: "White's first central target" },
      { square: "f7", label: "The bishop and queen can combine here" },
      { square: "d5", label: "Black's freeing counterbreak" },
      { square: "f4", label: "The Vienna Gambit's launch square" },
    ],
    pawnStructure: "Quiet lines keep pawns on e4 and d3; gambit lines advance f4 and may exchange on e5, opening the f-file and making development speed more important than structure.",
    mistakes: [
      "Playing f4 before noticing Black's ...d5 counterstrike",
      "Attacking f7 with too few developed pieces",
      "Leaving the king in the center after opening the f-file",
      "Moving Nc3 repeatedly instead of completing development",
    ],
    memoryTip: "Nc3 keeps the f-pawn free: develop first, then decide whether f4 is justified.",
    mainLine: line(
      "Vienna Gambit — central counterplay",
      VIENNA_START,
      [
        ply("g8", "f6", "Nf6", "Black develops with tempo against e4 and prepares the freeing ...d5 break."),
        ply("f2", "f4", "f4", "White offers a flank pawn to seize space and open attacking lines."),
        ply("d7", "d5", "d5", "Black counters in the center before White can consolidate the kingside initiative."),
        ply("f4", "e5", "fxe5", "White gains a tempo on the f6 knight and opens the f-file."),
        ply("f6", "e4", "Nxe4", "The knight uses the loosened center to occupy an active outpost and attack c3."),
        ply("g1", "f3", "Nf3", "White develops while challenging the centralized knight."),
        ply("f8", "e7", "Be7", "Black prepares castling and keeps the bishop out of a possible central tempo."),
        ply("d2", "d4", "d4", "White supports e5 and claims enough central space to justify the gambit play."),
        ply("e8", "g8", "O-O", "Black secures the king and activates the rook before the center opens further."),
      ],
    ),
    variations: [
      line(
        "Mieses Variation",
        VIENNA_START,
        [
          ply("g8", "f6", "Nf6", "Black develops with pressure on e4."),
          ply("g2", "g3", "g3", "White chooses a restrained fianchetto and reinforces the dark squares."),
          ply("d7", "d5", "d5", "Black uses the moment to challenge the center directly."),
          ply("e4", "d5", "exd5", "White removes the advanced pawn before completing development."),
          ply("f6", "d5", "Nxd5", "Black recaptures with a centralized knight and equal piece activity."),
          ply("f1", "g2", "Bg2", "The bishop takes the long diagonal and immediately questions d5."),
          ply("c7", "c6", "c6", "Black supports the knight and prepares a stable central structure."),
        ],
      ),
      line(
        "Frankenstein–Dracula Variation",
        VIENNA_START,
        [
          ply("g8", "f6", "Nf6", "Black attacks e4 and invites sharp play."),
          ply("f1", "c4", "Bc4", "White targets f7 and makes tactical use of quick development."),
          ply("f6", "e4", "Nxe4", "Black grabs the center pawn, accepting a forcing tactical test."),
          ply("d1", "h5", "Qh5", "The queen creates threats on f7 and e5, forcing Black to defend precisely."),
          ply("e4", "d6", "Nd6", "The knight retreats while guarding f7 and attacking the c4 bishop."),
          ply("c4", "b3", "Bb3", "White preserves the attacking bishop and keeps pressure on f7."),
          ply("b8", "c6", "Nc6", "Black develops another defender and controls b4 and d4."),
          ply("c3", "b5", "Nb5", "White brings the knight toward c7 and d6 to maintain tactical pressure."),
          ply("g7", "g6", "g6", "Black attacks the queen and buys time to organize the kingside."),
          ply("h5", "f3", "Qf3", "The queen retreats while keeping sight of f7 and the long diagonal."),
          ply("f7", "f5", "f5", "Black gains space and blocks the bishop's diagonal, though the king remains exposed."),
        ],
      ),
      line(
        "Max Lange Defense",
        VIENNA_START,
        [
          ply("b8", "c6", "Nc6", "Black defends e5 and develops without committing the kingside knight."),
          ply("g1", "f3", "Nf3", "White increases pressure on e5 and prepares to castle."),
          ply("g8", "f6", "Nf6", "Black develops symmetrically and reinforces central control."),
          ply("f1", "b5", "Bb5", "White pins the c6 knight and indirectly adds pressure to e5."),
          ply("f8", "b4", "Bb4", "Black answers with a pin of its own and creates balanced piece pressure."),
          ply("e1", "g1", "O-O", "White puts the king safely behind the rook and completes kingside development."),
          ply("e8", "g8", "O-O", "Black also secures the king before resolving the central tension."),
        ],
      ),
      line(
        "Anderssen Variation",
        VIENNA_START,
        [
          ply("g8", "f6", "Nf6", "Black develops and pressures e4."),
          ply("f1", "c4", "Bc4", "White places the bishop on its most aggressive diagonal toward f7."),
          ply("f8", "c5", "Bc5", "Black develops actively and points at f2."),
          ply("d2", "d3", "d3", "White secures e4 and opens the c1 bishop."),
          ply("d7", "d6", "d6", "Black stabilizes e5 and creates room for the c8 bishop."),
          ply("f2", "f4", "f4", "With the center supported, White begins a controlled kingside expansion."),
          ply("b8", "c6", "Nc6", "Black develops and adds pressure to the central dark squares."),
        ],
      ),
      line(
        "Vienna Gambit — Knight Capture",
        VIENNA_START,
        [
          ply("g8", "f6", "Nf6", "Black challenges e4 and prepares central play."),
          ply("f2", "f4", "f4", "White offers the f-pawn for time and open files."),
          ply("d7", "d5", "d5", "Black strikes at the center, the key response to a flank attack."),
          ply("f4", "e5", "fxe5", "White drives the f6 knight and keeps extra space."),
          ply("f6", "e4", "Nxe4", "The knight occupies the loosened e4 square and attacks c3."),
          ply("d1", "f3", "Qf3", "White attacks e4 twice and brings the queen toward f7."),
          ply("e4", "c3", "Nxc3", "Black removes the developed knight and disrupts White's queenside pawns."),
          ply("b2", "c3", "bxc3", "White restores material while opening the b-file and strengthening d4."),
        ],
      ),
    ],
    quiz: [
      quiz("Recognition", "Which move defines the Vienna Game after 1.e4 e5?", ["2.Nf3", "2.Nc3", "2.Bc4", "2.f4"], 1, "2.Nc3 supports e4 while deliberately leaving the f-pawn free."),
      quiz("Strategy", "Why does White often keep the knight off f3 at first?", ["To move the queen early", "To preserve f4", "To prevent ...d5", "To trade bishops"], 1, "The option of f4 gives the Vienna much of its flexible attacking character."),
      quiz("Counterplay", "What central break is Black seeking against an early f4?", ["...b5", "...g5", "...d5", "...a6"], 2, "...d5 attacks the center before White's kingside initiative is ready."),
      quiz("Tactics", "Which pawn is usually targeted by Bc4 and Qh5?", ["a7", "c7", "e5", "f7"], 3, "f7 is defended only by the king at the start of the game."),
      quiz("Mistake", "What makes a premature f4 risky?", ["It blocks Bc1", "It weakens the king and invites ...d5", "It loses Nc3", "It prevents castling forever"], 1, "Opening the f-file costs king cover, so development and central timing matter."),
    ],
  },
  {
    id: "kings-gambit",
    name: "King's Gambit",
    side: "White",
    difficulty: "Intermediate",
    style: ["Aggressive", "Tactical", "Gambit"],
    startingMoves: "1.e4 e5 2.f4",
    character: "Open files, rapid development, and direct king attacks",
    skillLevel: "Intermediate attackers",
    glyph: "♙",
    intro: "The King's Gambit offers the f-pawn to divert Black's e-pawn and accelerate an attack. It is less about recovering one pawn immediately than using open lines and faster development before Black can consolidate.",
    objectives: [
      "Deflect the e5 pawn and strengthen the center",
      "Open the f-file for a rook after castling",
      "Develop every attacking piece with tempo",
      "Prevent Black from safely holding the extra pawn",
      "Judge initiative more carefully than material",
    ],
    plans: {
      white: [
        "Play Nf3 to stop ...Qh4+ and accelerate castling.",
        "Use d4 to build a broad center while Black guards f4.",
        "Bring Bc4 and the queen toward f7.",
        "Open the f-file, then place a rook on f1.",
      ],
      black: [
        "Return the pawn if it completes development safely.",
        "Challenge White's center with ...d5.",
        "Use ...g5 only when the kingside can withstand open lines.",
        "Trade attacking pieces and force White to prove compensation.",
      ],
    },
    keySquares: [
      { square: "f4", label: "The offered pawn and source of the open file" },
      { square: "f7", label: "White's natural attacking focus" },
      { square: "e4", label: "White's central anchor" },
      { square: "d5", label: "Black's best freeing break" },
    ],
    pawnStructure: "White often keeps e4 and d4 while the f-pawn disappears. Black may hold a pawn on f4 with ...g5, creating extra material but also loose kingside dark squares.",
    mistakes: [
      "Trying to win the gambit pawn back before developing",
      "Allowing ...Qh4+ by delaying Nf3 without a reason",
      "Opening the f-file but leaving the king in the center",
      "Sacrificing more material without bringing new pieces into the attack",
    ],
    memoryTip: "The pawn buys time and open lines; spend both on development.",
    mainLine: line(
      "King's Knight Gambit",
      KINGS_GAMBIT_START,
      [
        ply("e5", "f4", "exf4", "Black accepts the pawn, gives up the e5 strongpoint, and asks White to prove compensation."),
        ply("g1", "f3", "Nf3", "White prevents ...Qh4+ and develops toward immediate castling."),
        ply("g7", "g5", "g5", "Black tries to secure the extra pawn, but advances pawns in front of the king."),
        ply("h2", "h4", "h4", "White attacks the pawn chain at its base to open the h- and f-files."),
        ply("g5", "g4", "g4", "Black gains space and drives the knight, accepting further kingside looseness."),
        ply("f3", "e5", "Ne5", "The knight centralizes with threats on f7, g4, and c4."),
        ply("g8", "f6", "Nf6", "Black develops, challenges e4, and prepares to secure the king."),
        ply("d2", "d4", "d4", "White builds the ideal pawn center while Black's e-pawn is gone."),
        ply("d7", "d6", "d6", "Black questions the centralized knight and opens the c8 bishop."),
      ],
    ),
    variations: [
      line(
        "Classical Declined",
        KINGS_GAMBIT_START,
        [
          ply("f8", "c5", "Bc5", "Black declines the pawn and develops toward f2, keeping the center intact."),
          ply("g1", "f3", "Nf3", "White controls h4, attacks e5, and prepares castling."),
          ply("d7", "d6", "d6", "Black supports e5 and opens the c8 bishop."),
          ply("c2", "c3", "c3", "White prepares d4 so the center can be challenged with support."),
          ply("g8", "f6", "Nf6", "Black develops with pressure on e4."),
          ply("d2", "d4", "d4", "White uses the extra central support to confront e5."),
          ply("e5", "d4", "exd4", "Black releases the tension before White can advance further."),
        ],
      ),
      line(
        "Falkbeer Countergambit",
        KINGS_GAMBIT_START,
        [
          ply("d7", "d5", "d5", "Black refuses to defend passively and counteroffers a pawn in the center."),
          ply("e4", "d5", "exd5", "White removes the central challenger and temporarily gains space."),
          ply("e5", "e4", "e4", "Black advances with tempo, taking space and restricting the g1 knight."),
          ply("d2", "d3", "d3", "White attacks the advanced pawn and opens the c1 bishop."),
          ply("g8", "f6", "Nf6", "Black develops behind the space-gaining e4 pawn."),
          ply("d3", "e4", "dxe4", "White eliminates the cramping pawn before it can be fully supported."),
          ply("f6", "e4", "Nxe4", "Black recaptures with an active knight and restores material balance."),
        ],
      ),
      line(
        "Bishop's Gambit",
        KINGS_GAMBIT_START,
        [
          ply("e5", "f4", "exf4", "Black accepts and removes the e5 pawn from the center."),
          ply("f1", "c4", "Bc4", "White develops directly toward f7 and accepts the possibility of ...Qh4+."),
          ply("g8", "f6", "Nf6", "Black develops, attacks e4, and prepares king safety."),
          ply("b1", "c3", "Nc3", "White reinforces e4 and brings another piece into the attack."),
          ply("c7", "c6", "c6", "Black prepares ...d5 to blunt the c4 bishop."),
          ply("d2", "d4", "d4", "White uses the missing e-pawn to establish a broad center."),
          ply("d7", "d5", "d5", "Black hits the center before White can castle and coordinate fully."),
        ],
      ),
      line(
        "Muzio Gambit",
        KINGS_GAMBIT_START,
        [
          ply("e5", "f4", "exf4", "Black accepts the first pawn and opens White's f-file."),
          ply("g1", "f3", "Nf3", "White develops and blocks the immediate queen check on h4."),
          ply("g7", "g5", "g5", "Black tries to hold f4 with a pawn chain."),
          ply("f1", "c4", "Bc4", "White aims at f7 and clears the way to castle."),
          ply("g5", "g4", "g4", "Black attacks the f3 knight and commits more kingside pawns."),
          ply("e1", "g1", "O-O", "White deliberately offers the knight to gain an open f-file and a lead in development."),
          ply("g4", "f3", "gxf3", "Black accepts the piece, taking material while opening lines toward its own king."),
          ply("d1", "f3", "Qxf3", "White recaptures the pawn, centralizes the queen, and creates immediate threats on f7."),
        ],
      ),
      line(
        "Modern Defense to the Gambit",
        KINGS_GAMBIT_START,
        [
          ply("e5", "f4", "exf4", "Black accepts the pawn but plans development rather than a pawn chain."),
          ply("g1", "f3", "Nf3", "White develops and stops the checking resource ...Qh4+."),
          ply("d7", "d6", "d6", "Black prepares ...g5 only under better control and frees the c8 bishop."),
          ply("d2", "d4", "d4", "White occupies the center and opens the c1 bishop."),
          ply("g7", "g5", "g5", "Black now supports the extra pawn after preparing development."),
          ply("h2", "h4", "h4", "White attacks the pawn chain before it can become stable."),
          ply("g5", "g4", "g4", "Black gains space and forces the knight to choose an active square."),
          ply("f3", "g1", "Ng1", "The knight retreats to preserve material while White plans to undermine g4."),
        ],
      ),
    ],
    quiz: [
      quiz("Recognition", "Which move offers the King's Gambit?", ["2.Nf3", "2.Bc4", "2.f4", "2.d4"], 2, "2.f4 offers a flank pawn to deflect Black's e5 pawn."),
      quiz("Concept", "What is White primarily buying with the pawn?", ["An endgame", "Time and open lines", "A queen trade", "A protected passed pawn"], 1, "Development time and the open f-file are the gambit's real compensation."),
      quiz("Defense", "Why is 3.Nf3 so common after ...exf4?", ["It attacks f4 twice", "It prevents ...Qh4+ and develops", "It forces ...g5", "It trades queens"], 1, "Nf3 is both a defensive and developmental move."),
      quiz("Counterplay", "Which central response defines the Falkbeer Countergambit?", ["...d5", "...c5", "...f5", "...b5"], 0, "Black counters a wing gambit by striking in the center with ...d5."),
      quiz("Mistake", "What should White avoid after sacrificing f4?", ["Castling", "Developing Bc4", "Spending more tempi only to regain the pawn", "Playing d4"], 2, "The initiative disappears if White neglects development to chase one pawn."),
    ],
  },
  {
    id: "scandinavian",
    name: "Scandinavian Defense",
    side: "Black",
    difficulty: "Beginner",
    style: ["Direct", "Solid", "Beginner Friendly"],
    startingMoves: "1.e4 d5",
    character: "Immediate central clarification with a clear setup",
    skillLevel: "Beginner to intermediate",
    glyph: "♛",
    intro: "The Scandinavian attacks e4 on move one and usually accepts that the queen or a knight will recapture on d5. Black gives White a few developing tempi but gains a dependable structure and straightforward piece placement.",
    objectives: [
      "Challenge White's center immediately",
      "Recapture d5 without letting the queen become trapped",
      "Build a compact c6–e6 pawn structure",
      "Develop the light-squared bishop before ...e6 when possible",
      "Finish development after the early queen move",
    ],
    plans: {
      white: [
        "Develop Nc3 with tempo against the queen.",
        "Use d4 and Nf3 to build a central lead in development.",
        "Avoid chasing the queen if it neglects real piece development.",
        "Target Black's slightly slower kingside coordination.",
      ],
      black: [
        "Place the queen on a5, d6, or d8 according to the setup.",
        "Play ...c6 and ...Bf5 before closing the c8 bishop.",
        "Use ...Nf6 and ...e6 to attack White's center.",
        "Trade a few pieces if White's development lead becomes dangerous.",
      ],
    },
    keySquares: [
      { square: "d5", label: "The opening's first exchange point" },
      { square: "a5", label: "The queen's active main-line retreat" },
      { square: "c6", label: "The structure's stabilizing pawn" },
      { square: "f5", label: "The light bishop's best square before ...e6" },
    ],
    pawnStructure: "Black commonly builds pawns on c6 and e6 around an empty d5 square. The structure is sound, but Black must avoid becoming passive while White enjoys extra space.",
    mistakes: [
      "Moving the queen repeatedly just to attack loose pawns",
      "Playing ...e6 before finding a role for the c8 bishop",
      "Ignoring White's lead in development",
      "Assuming an early queen move makes every queen chase harmless",
    ],
    memoryTip: "Clarify e4, park the queen safely, then develop without another delay.",
    mainLine: line(
      "Main Line with ...Qa5",
      SCANDINAVIAN_START,
      [
        ply("d8", "d5", "Qxd5", "The queen restores material immediately and makes White gain time with development."),
        ply("b1", "c3", "Nc3", "White develops with tempo by attacking the exposed queen."),
        ply("d5", "a5", "Qa5", "The queen stays active, pins the c3 knight to the king, and watches a2."),
        ply("d2", "d4", "d4", "White builds a broad center while the queen is away from home."),
        ply("g8", "f6", "Nf6", "Black develops against e4 and prepares to castle."),
        ply("g1", "f3", "Nf3", "White supports d4 and prepares kingside safety."),
        ply("c7", "c6", "c6", "Black gives the queen a retreat and supports a later ...Bf5 or ...e6 setup."),
        ply("f1", "c4", "Bc4", "White develops toward f7 and takes advantage of the open diagonal."),
        ply("c8", "f5", "Bf5", "Black activates the problem bishop before locking it behind ...e6."),
      ],
    ),
    variations: [
      line(
        "Main Line with ...Qd6",
        SCANDINAVIAN_START,
        [
          ply("d8", "d5", "Qxd5", "Black recovers the pawn at once."),
          ply("b1", "c3", "Nc3", "White develops while attacking the queen."),
          ply("d5", "d6", "Qd6", "The queen supports e5 and h2 while avoiding a future discovered attack on a5."),
          ply("d2", "d4", "d4", "White establishes central space and frees the c1 bishop."),
          ply("g8", "f6", "Nf6", "Black develops with pressure on e4."),
          ply("g1", "f3", "Nf3", "White supports the center and prepares castling."),
          ply("c7", "c6", "c6", "Black creates a stable shell and prepares ...Bf5."),
        ],
      ),
      line(
        "Classical Retreat ...Qd8",
        SCANDINAVIAN_START,
        [
          ply("d8", "d5", "Qxd5", "Black restores material immediately."),
          ply("b1", "c3", "Nc3", "White gains a developing tempo on the queen."),
          ply("d5", "d8", "Qd8", "Black accepts the lost tempo to keep the queen completely safe."),
          ply("d2", "d4", "d4", "White uses the extra time to construct a full center."),
          ply("g8", "f6", "Nf6", "Black begins normal development and attacks e4."),
          ply("g1", "f3", "Nf3", "White protects the center and prepares castling."),
          ply("c7", "c6", "c6", "Black supports d5 and creates room for the queen on c7 if needed."),
        ],
      ),
      line(
        "Modern Variation",
        SCANDINAVIAN_START,
        [
          ply("g8", "f6", "Nf6", "Black delays the recapture, developing a piece instead of exposing the queen."),
          ply("d2", "d4", "d4", "White supports the extra pawn and establishes a broad center."),
          ply("f6", "d5", "Nxd5", "The knight recovers the pawn while occupying a central square."),
          ply("g1", "f3", "Nf3", "White develops and controls e5 and g5."),
          ply("g7", "g6", "g6", "Black prepares a fianchetto to pressure d4."),
          ply("c2", "c4", "c4", "White gains space and drives the central knight."),
          ply("d5", "b6", "Nb6", "The knight retreats to a stable square and eyes c4 and a4."),
        ],
      ),
      line(
        "Portuguese Variation",
        SCANDINAVIAN_START,
        [
          ply("g8", "f6", "Nf6", "Black develops first and postpones recovering the d5 pawn."),
          ply("d2", "d4", "d4", "White reinforces the extra pawn and opens the c1 bishop."),
          ply("c8", "g4", "Bg4", "Black develops with a pin, increasing pressure on d4 and e2."),
          ply("f2", "f3", "f3", "White breaks the pin but loosens the king and dark squares."),
          ply("g4", "f5", "Bf5", "The bishop preserves itself while continuing to pressure c2 and e4."),
          ply("f1", "b5", "Bb5+", "White checks with development and makes Black commit the c-pawn."),
          ply("c7", "c6", "c6", "Black blocks the check, supports d5, and gains a tempo on the bishop."),
        ],
      ),
      line(
        "Icelandic Gambit",
        SCANDINAVIAN_START,
        [
          ply("g8", "f6", "Nf6", "Black develops and attacks the extra d5 pawn."),
          ply("c2", "c4", "c4", "White protects d5 with space but delays kingside development."),
          ply("e7", "e6", "e6", "Black offers another pawn to open lines and accelerate development."),
          ply("d5", "e6", "dxe6", "White accepts, taking material but giving Black open diagonals."),
          ply("c8", "e6", "Bxe6", "The light-squared bishop recaptures with tempo and develops to an active square."),
          ply("g1", "f3", "Nf3", "White finally develops and prepares king safety."),
          ply("b8", "c6", "Nc6", "Black adds another piece to the center and increases the development lead."),
        ],
      ),
    ],
    quiz: [
      quiz("Recognition", "What move starts the Scandinavian Defense?", ["1...c5", "1...e6", "1...d5", "1...Nf6"], 2, "1...d5 attacks the e4 pawn immediately."),
      quiz("Main line", "After ...Qxd5 and Nc3, where is the most active traditional queen retreat?", ["a5", "h5", "d6 only", "e4"], 0, "...Qa5 keeps pressure on c3 and remains outside the center."),
      quiz("Development", "Why is ...Bf5 often played before ...e6?", ["To win the queen", "To avoid trapping the c8 bishop", "To stop castling", "To protect a5"], 1, "Once ...e6 is played, the c8 bishop has less scope."),
      quiz("Modern line", "What does 2...Nf6 avoid?", ["A pawn exchange", "An early queen exposure", "White playing d4", "Kingside castling"], 1, "Black develops a knight and plans to recover d5 without moving the queen out."),
      quiz("Mistake", "What is Black's greatest practical risk?", ["Too many pawns", "Falling behind in development", "A trapped a8 rook", "An illegal queen move"], 1, "The early queen recapture gives White tempi, so Black must develop efficiently."),
    ],
  },
  {
    id: "pirc",
    name: "Pirc Defense",
    side: "Black",
    difficulty: "Intermediate",
    style: ["Hypermodern", "Dynamic", "Strategic"],
    startingMoves: "1.e4 d6 2.d4 Nf6 3.Nc3 g6",
    character: "A flexible defense that attacks an allowed pawn center",
    skillLevel: "Intermediate",
    glyph: "♝",
    intro: "The Pirc lets White build a large center, then attacks it with pieces, pawn breaks, and the g7 bishop. Black must understand timing: passive waiting leaves no space, while a well-timed ...e5, ...c5, or ...b5 creates dynamic counterplay.",
    objectives: [
      "Invite White's center without surrendering control of it",
      "Fianchetto the bishop toward d4 and b2",
      "Castle before opening the position",
      "Choose the right break between ...e5 and ...c5",
      "Create queenside play against White's kingside ambitions",
    ],
    plans: {
      white: [
        "Use the space advantage to prepare e5 or f4–f5.",
        "In the 150 Attack, combine Be3, Qd2, and a kingside pawn storm.",
        "Keep d4 securely defended before launching an attack.",
        "Prevent Black's queenside expansion from becoming too fast.",
      ],
      black: [
        "Complete Bg7 and castling before counterattacking.",
        "Use ...e5 to challenge d4 or ...c5 to pressure the center from the side.",
        "Play ...b5 when White castles queenside or commits to a kingside attack.",
        "Attack central pawn bases instead of chasing the advanced pawns directly.",
      ],
    },
    keySquares: [
      { square: "d4", label: "The center's main base and bishop target" },
      { square: "e5", label: "Black's direct central break" },
      { square: "c5", label: "Black's flank pressure on d4" },
      { square: "b5", label: "The queenside counterplay lever" },
    ],
    pawnStructure: "White often owns e4 and d4, sometimes adding f4. Black keeps d6 and g6, then undermines the broad center with ...e5 or ...c5 rather than trying to occupy equal space immediately.",
    mistakes: [
      "Fianchettoing and then waiting without a pawn break",
      "Playing ...e5 when White can close the center with d5 and attack freely",
      "Starting queenside play before the king is safe",
      "Underestimating White's f4–f5 attacking tempo",
    ],
    memoryTip: "Let the center advance, then attack its base before it attacks your king.",
    mainLine: line(
      "Classical System",
      PIRC_START,
      [
        ply("g1", "f3", "Nf3", "White develops calmly, protects e5, and keeps the f-pawn structure sound."),
        ply("f8", "g7", "Bg7", "Black completes the fianchetto and puts long-range pressure on d4."),
        ply("f1", "e2", "Be2", "White prepares castling without revealing an aggressive setup too early."),
        ply("e8", "g8", "O-O", "Black secures the king before challenging the center."),
        ply("e1", "g1", "O-O", "White also removes the king from the central files."),
        ply("c7", "c6", "c6", "Black supports ...b5 and prepares a flexible ...e5 or ...Nbd7 setup."),
      ],
    ),
    variations: [
      line(
        "Austrian Attack",
        PIRC_START,
        [
          ply("f2", "f4", "f4", "White builds the largest possible center and prepares e5 or f5."),
          ply("f8", "g7", "Bg7", "Black develops directly against the central d4 pawn."),
          ply("g1", "f3", "Nf3", "White reinforces e5 and brings another piece toward the attack."),
          ply("e8", "g8", "O-O", "Black secures the king before striking back."),
          ply("f1", "d3", "Bd3", "White eyes h7 and supports the central e4 pawn."),
          ply("b8", "a6", "Na6", "Black develops toward c5, where the knight can pressure d3 and b3."),
        ],
      ),
      line(
        "150 Attack",
        PIRC_START,
        [
          ply("c1", "e3", "Be3", "White develops with the idea of Qd2 and opposite-side castling."),
          ply("f8", "g7", "Bg7", "Black activates the long diagonal against d4."),
          ply("d1", "d2", "Qd2", "White connects the bishop and queen, preparing Bh6 and queenside castling."),
          ply("c7", "c6", "c6", "Black prepares ...b5 counterplay against the side where White may castle."),
          ply("f2", "f3", "f3", "White gives e4 extra support and prepares g4 without allowing ...Ng4."),
          ply("b7", "b5", "b5", "Black starts queenside expansion before White's kingside attack arrives."),
        ],
      ),
      line(
        "Byrne Variation",
        PIRC_START,
        [
          ply("c1", "g5", "Bg5", "White pins the f6 knight and makes ...e5 harder to arrange."),
          ply("f8", "g7", "Bg7", "Black completes the fianchetto and pressure on d4."),
          ply("d1", "d2", "Qd2", "White supports the bishop and prepares long castling."),
          ply("c7", "c6", "c6", "Black prepares queenside space and gives the queen a useful c7 square."),
          ply("f2", "f4", "f4", "White expands and supports the e5 advance."),
          ply("b7", "b5", "b5", "Black creates immediate play on the opposite wing."),
        ],
      ),
      line(
        "Czech Variation",
        PIRC_START.slice(0, 5),
        [
          ply("c7", "c6", "c6", "Black builds a sturdier center and prepares ...e5 without fianchettoing immediately."),
          ply("f2", "f4", "f4", "White takes more space and threatens e5."),
          ply("d8", "a5", "Qa5", "Black pins c3, pressures e4, and discourages an easy central advance."),
          ply("f1", "d3", "Bd3", "White completes kingside development and supports e4."),
          ply("e7", "e5", "e5", "Black finally challenges the center with c6 supporting the structure."),
        ],
      ),
      line(
        "Chinese Variation",
        PIRC_START,
        [
          ply("g1", "f3", "Nf3", "White chooses the sound Classical development."),
          ply("f8", "g7", "Bg7", "Black completes the key fianchetto."),
          ply("f1", "e2", "Be2", "White prepares castling and keeps the center stable."),
          ply("e8", "g8", "O-O", "Black makes the king safe."),
          ply("e1", "g1", "O-O", "White finishes kingside development."),
          ply("c7", "c6", "c6", "Black prepares the characteristic queenside expansion."),
          ply("f1", "e1", "Re1", "White reinforces e4 and supports a future e5 push."),
          ply("b7", "b5", "b5", "Black gains queenside space and prepares ...Nbd7 and ...e5."),
        ],
      ),
    ],
    quiz: [
      quiz("Recognition", "Which setup identifies the Pirc?", ["...d6, ...Nf6, ...g6", "...e6 and ...d5", "...c6 and ...d5", "...f5 and ...Nf6"], 0, "Black combines ...d6, ...Nf6, and ...g6 against White's e4–d4 center."),
      quiz("Concept", "Why does Black allow White a large center?", ["It cannot be attacked", "To undermine it later", "To trade queens", "To win a rook"], 1, "The Pirc is hypermodern: pieces and pawn breaks target the advanced center."),
      quiz("Attack", "Which move marks the Austrian Attack?", ["4.Bg5", "4.Be3", "4.f4", "4.g3"], 2, "4.f4 builds a three-pawn attacking center."),
      quiz("Counterplay", "Which breaks most often challenge White's center?", ["...a5 and ...h5", "...e5 and ...c5", "...f6 and ...g5", "...b6 and ...Bb7 only"], 1, "...e5 and ...c5 attack the base and key squares of White's center."),
      quiz("Mistake", "What happens if Black only fianchettos and waits?", ["Black wins the center", "Black may become cramped", "White must trade queens", "The g7 bishop is trapped permanently"], 1, "The setup needs an active pawn break; otherwise White's space advantage grows unchecked."),
    ],
  },
  {
    id: "alekhine",
    name: "Alekhine Defense",
    side: "Black",
    difficulty: "Intermediate",
    style: ["Hypermodern", "Dynamic", "Provocative"],
    startingMoves: "1.e4 Nf6",
    character: "Provokes space, then attacks the extended center",
    skillLevel: "Intermediate",
    glyph: "♞",
    intro: "Alekhine's Defense invites e5 and further pawn advances, betting that White's center will become easier to attack than to maintain. Black must know when to stop retreating and begin undermining with ...d6 and ...c5.",
    objectives: [
      "Provoke White's e-pawn into an advanced position",
      "Induce a broad center that needs constant support",
      "Break with ...d6 and often ...c5",
      "Trade the central pawns before they can advance safely",
      "Develop rapidly once the knight reaches a stable square",
    ],
    plans: {
      white: [
        "Use the space gain to develop behind the pawn center.",
        "Avoid advancing more pawns than can be defended.",
        "Meet ...d6 by choosing whether to exchange, advance, or support e5.",
        "Exploit Black's temporary loss of development time.",
      ],
      black: [
        "Attack e5 with ...d6 and piece pressure.",
        "Use ...c5 against the base on d4.",
        "Retreat the knight to b6 rather than let it be trapped.",
        "Trade central pawns and target the squares left behind.",
      ],
    },
    keySquares: [
      { square: "e5", label: "The advanced pawn Black tries to undermine" },
      { square: "d4", label: "The broad center's supporting base" },
      { square: "b6", label: "The knight's stable retreat square" },
      { square: "c5", label: "Black's pressure against d4" },
    ],
    pawnStructure: "White often builds e5, d4, and c4, gaining space but creating a chain Black can hit with ...d6 and ...c5. Exchanges usually leave useful targets on the central dark squares.",
    mistakes: [
      "Retreating the knight repeatedly without attacking the center",
      "Allowing White to stabilize every advanced pawn",
      "Playing ...d6 before being ready to recapture or pressure e5",
      "White advancing c5 too early and giving the knight a clear route",
    ],
    memoryTip: "Invite the pawns forward, then attack the chain before it becomes permanent.",
    mainLine: line(
      "Modern Variation",
      ALEKHINE_START,
      [
        ply("d2", "d4", "d4", "White supports e5 and constructs a broad center."),
        ply("d7", "d6", "d6", "Black immediately challenges the head of the pawn chain."),
        ply("g1", "f3", "Nf3", "White develops while giving d4 and e5 more support."),
        ply("d6", "e5", "dxe5", "Black removes the advanced pawn before White can reinforce it further."),
        ply("f3", "e5", "Nxe5", "White recaptures with development and centralizes the knight."),
        ply("c7", "c6", "c6", "Black takes d5 away from the knight and prepares ...Bf5 or ...Nd7."),
        ply("f1", "e2", "Be2", "White prepares castling and keeps the center comfortably supported."),
        ply("c8", "f5", "Bf5", "Black develops outside the pawn chain and targets c2."),
      ],
    ),
    variations: [
      line(
        "Four Pawns Attack",
        ALEKHINE_START,
        [
          ply("d2", "d4", "d4", "White reinforces e5 and claims more space."),
          ply("d7", "d6", "d6", "Black attacks the advanced e5 pawn."),
          ply("c2", "c4", "c4", "White drives the d5 knight and creates a three-pawn center."),
          ply("d5", "b6", "Nb6", "The knight reaches safety while watching c4 and d5."),
          ply("f2", "f4", "f4", "White completes the four-pawn formation and prepares further expansion."),
          ply("d6", "e5", "dxe5", "Black starts dismantling the center before it can advance."),
          ply("f4", "e5", "fxe5", "White keeps a space-gaining pawn on e5 but opens the f-file."),
          ply("b8", "c6", "Nc6", "Black develops with immediate pressure on e5 and d4."),
        ],
      ),
      line(
        "Exchange Variation",
        ALEKHINE_START,
        [
          ply("d2", "d4", "d4", "White builds the center and supports e5."),
          ply("d7", "d6", "d6", "Black challenges the advanced pawn chain."),
          ply("c2", "c4", "c4", "White gains space and forces the knight from d5."),
          ply("d5", "b6", "Nb6", "The knight retreats to a stable square."),
          ply("e5", "d6", "exd6", "White releases the tension to reduce Black's immediate attacks on e5."),
          ply("c7", "d6", "cxd6", "Black recaptures toward the center and opens the c-file."),
          ply("b1", "c3", "Nc3", "White develops against d5 and supports the central pawns."),
          ply("g7", "g6", "g6", "Black prepares a fianchetto to pressure d4."),
        ],
      ),
      line(
        "Chase Variation",
        ALEKHINE_START,
        [
          ply("c2", "c4", "c4", "White chases the knight immediately and gains queenside space."),
          ply("d5", "b6", "Nb6", "The knight uses its safest route while keeping pressure on c4."),
          ply("c4", "c5", "c5", "White gains more space and takes d6 away from Black's pieces."),
          ply("b6", "d5", "Nd5", "The knight returns to the central outpost because c5 no longer attacks it."),
          ply("f1", "c4", "Bc4", "White develops with tempo against the centralized knight and f7."),
          ply("e7", "e6", "e6", "Black supports d5 and opens the f8 bishop."),
          ply("b1", "c3", "Nc3", "White adds a second attacker to d5 and completes queenside development."),
        ],
      ),
      line(
        "Two Pawns Attack",
        ALEKHINE_START,
        [
          ply("c2", "c4", "c4", "White gains space and forces another knight decision."),
          ply("d5", "b6", "Nb6", "The knight retreats while pressuring c4."),
          ply("d2", "d4", "d4", "White constructs a strong e5–d4 pawn duo."),
          ply("d7", "d6", "d6", "Black attacks the head of the chain."),
          ply("e5", "d6", "exd6", "White exchanges before Black can intensify pressure on e5."),
          ply("c7", "d6", "cxd6", "Black recaptures centrally and opens the c-file."),
          ply("b1", "c3", "Nc3", "White develops with pressure on d5 and b5."),
        ],
      ),
      line(
        "Scandinavian Variation",
        ALEKHINE_START,
        [
          ply("d2", "d4", "d4", "White supports the advanced pawn and controls central space."),
          ply("d7", "d6", "d6", "Black begins the standard attack on e5."),
          ply("f1", "c4", "Bc4", "White develops actively and puts pressure on f7."),
          ply("d5", "b6", "Nb6", "The knight moves away from the bishop's tempo and eyes c4."),
          ply("c4", "b3", "Bb3", "White preserves the bishop's diagonal toward f7."),
          ply("d6", "e5", "dxe5", "Black removes the advanced pawn and opens the d-file."),
          ply("d4", "e5", "dxe5", "White recaptures with the d-pawn, keeping central space."),
          ply("d8", "d1", "Qxd1+", "Black uses the opened d-file to trade queens and reduce White's initiative."),
          ply("e1", "d1", "Kxd1", "White restores material but gives up castling rights in the simplified position."),
        ],
      ),
    ],
    quiz: [
      quiz("Recognition", "What provocative move starts Alekhine's Defense?", ["1...d5", "1...Nf6", "1...g6", "1...c5"], 1, "1...Nf6 attacks e4 and invites the pawn to advance."),
      quiz("Concept", "What does Black hope White will create?", ["A weak extended center", "An open a-file", "Doubled kingside pawns immediately", "A forced queen trade"], 0, "Advanced pawns provide space but also targets and squares behind them."),
      quiz("Main break", "Which move attacks White's advanced e5 pawn?", ["...a6", "...h6", "...d6", "...b5"], 2, "...d6 is the standard undermining break."),
      quiz("Space", "Which variation builds e5, d4, c4, and f4?", ["Exchange", "Four Pawns Attack", "Chase", "Modern"], 1, "The Four Pawns Attack creates maximum space and maximum responsibility."),
      quiz("Mistake", "What must Black do after provoking pawn advances?", ["Keep retreating", "Attack the center", "Trade the a-pawn", "Move the queen repeatedly"], 1, "Provocation only works if Black follows with timely pressure and pawn breaks."),
    ],
  },
  {
    id: "nimzo-indian",
    name: "Nimzo-Indian Defense",
    side: "Black",
    difficulty: "Intermediate",
    style: ["Positional", "Dynamic", "Strategic"],
    startingMoves: "1.d4 Nf6 2.c4 e6 3.Nc3 Bb4",
    character: "Piece pressure, structural choices, and control of e4",
    skillLevel: "Intermediate to advanced",
    glyph: "♝",
    intro: "The Nimzo-Indian pins White's c3 knight before committing to ...d5. Black can trade the bishop for doubled c-pawns, use the pin to prevent e4, or shift into active central play. It is a model opening for balancing bishop pair, structure, and development.",
    objectives: [
      "Prevent or delay White's e4 expansion",
      "Use the pin to create structural concessions",
      "Choose between ...d5 and ...c5 central play",
      "Trade on c3 only when the doubled pawns can be targeted",
      "Develop rapidly around a flexible pawn center",
    ],
    plans: {
      white: [
        "Use Qc2 to protect c3 and preserve the pawn structure.",
        "Choose e3 for safe development or a3 for the bishop pair.",
        "Build e4 only when the pin and central pressure are resolved.",
        "Use the bishop pair if Black exchanges on c3.",
      ],
      black: [
        "Pressure c3 and e4 with pieces before fixing the center.",
        "Attack doubled c-pawns after ...Bxc3+.",
        "Use ...c5 against d4 in Rubinstein structures.",
        "Complete castling before opening the central files.",
      ],
    },
    keySquares: [
      { square: "e4", label: "The central expansion Black restrains" },
      { square: "c3", label: "The pinned knight and structural decision" },
      { square: "c5", label: "Black's active pressure against d4" },
      { square: "e3", label: "White's solid Rubinstein setup" },
    ],
    pawnStructure: "After ...Bxc3+, White may have doubled c3–c4 pawns and the bishop pair. Black targets the fixed pawns; White seeks central space and open lines for the bishops.",
    mistakes: [
      "Giving up the b4 bishop without a structural reason",
      "Allowing e4 without counterplay",
      "Attacking c3 while neglecting development",
      "White assuming the bishop pair automatically compensates for weak pawns",
    ],
    memoryTip: "Pin Nc3 to restrain e4; exchange only when the structure becomes a target.",
    mainLine: line(
      "Rubinstein System",
      NIMZO_START,
      [
        ply("e2", "e3", "e3", "White builds a solid center and opens the f1 bishop without deciding the queen's role."),
        ply("e8", "g8", "O-O", "Black makes the king safe while preserving every central option."),
        ply("f1", "d3", "Bd3", "White develops toward h7 and prepares Nf3."),
        ply("d7", "d5", "d5", "Black establishes a firm center and directly contests e4."),
        ply("g1", "f3", "Nf3", "White supports d4 and completes the natural kingside setup."),
        ply("c7", "c5", "c5", "Black increases pressure on d4 before White can expand with e4."),
      ],
    ),
    variations: [
      line(
        "Classical / Capablanca Variation",
        NIMZO_START,
        [
          ply("d1", "c2", "Qc2", "White protects c3 with the queen and prepares e4 without accepting doubled pawns."),
          ply("e8", "g8", "O-O", "Black castles and waits to see White's center."),
          ply("a2", "a3", "a3", "White asks the b4 bishop to decide whether to exchange or retreat."),
          ply("b4", "c3", "Bxc3+", "Black gives up the bishop to damage White's structure before retreating costs time."),
          ply("c2", "c3", "Qxc3", "The queen recaptures, preserving healthy pawns and gaining the bishop pair."),
          ply("d7", "d5", "d5", "Black strikes in the center before White's bishops become active."),
        ],
      ),
      line(
        "Sämisch Variation",
        NIMZO_START,
        [
          ply("a2", "a3", "a3", "White immediately challenges the bishop and accepts structural damage for the bishop pair."),
          ply("b4", "c3", "Bxc3+", "Black doubles the c-pawns and removes the knight that supported e4."),
          ply("b2", "c3", "bxc3", "White opens the b-file and gains a broad center at the cost of doubled pawns."),
          ply("e8", "g8", "O-O", "Black secures the king before attacking the structure."),
          ply("f2", "f3", "f3", "White reinforces e4 and prepares a large pawn center."),
          ply("d7", "d5", "d5", "Black challenges the center before e4 can be played comfortably."),
        ],
      ),
      line(
        "Leningrad Variation",
        NIMZO_START,
        [
          ply("c1", "g5", "Bg5", "White pins the f6 knight and increases the possibility of e4."),
          ply("h7", "h6", "h6", "Black questions the bishop before committing the center."),
          ply("g5", "h4", "Bh4", "White maintains the pin and keeps pressure on f6."),
          ply("c7", "c5", "c5", "Black attacks d4 from the flank and creates queenside space."),
          ply("d4", "d5", "d5", "White gains space and closes the immediate pressure on d4."),
          ply("d7", "d6", "d6", "Black restrains e5 and prepares to undermine the advanced center."),
        ],
      ),
      line(
        "Hübner Variation",
        NIMZO_START,
        [
          ply("e2", "e3", "e3", "White chooses the solid Rubinstein setup."),
          ply("c7", "c5", "c5", "Black attacks d4 before occupying the center with ...d5."),
          ply("f1", "d3", "Bd3", "White develops and prepares kingside castling."),
          ply("b8", "c6", "Nc6", "Black adds pressure to d4 and e5."),
          ply("g1", "f3", "Nf3", "White completes natural development and supports d4."),
          ply("b4", "c3", "Bxc3+", "Now the exchange fixes doubled pawns that Black can attack with ...d6 and ...e5."),
          ply("b2", "c3", "bxc3", "White accepts the structure in return for central control and the bishop pair."),
          ply("d7", "d6", "d6", "Black builds a dark-square blockade and prepares ...e5."),
        ],
      ),
      line(
        "Kasparov Variation",
        NIMZO_START,
        [
          ply("g1", "f3", "Nf3", "White develops without deciding whether the e-pawn or queen should address the pin."),
          ply("e8", "g8", "O-O", "Black castles and preserves central flexibility."),
          ply("c1", "g5", "Bg5", "White pins the defender of e4 and d5."),
          ply("h7", "h6", "h6", "Black asks the bishop to declare its intentions."),
          ply("g5", "h4", "Bh4", "White preserves the pin and keeps the bishop active."),
          ply("d7", "d5", "d5", "Black occupies the center before White can play e4."),
        ],
      ),
    ],
    quiz: [
      quiz("Recognition", "Which move completes the Nimzo-Indian setup?", ["3...d5", "3...Bb4", "3...c5", "3...b6"], 1, "3...Bb4 pins Nc3 and restrains e4."),
      quiz("Concept", "What central move is the pin designed to restrain?", ["e4", "c5", "f4", "b4"], 0, "Nc3 supports e4, so pinning it reduces White's central control."),
      quiz("Structure", "What does ...Bxc3+ often create?", ["An isolated e-pawn", "Doubled c-pawns", "A passed h-pawn", "A trapped queen"], 1, "The structural weakness can compensate Black for surrendering the bishop pair."),
      quiz("Variation", "Which fourth move defines the Classical Variation?", ["4.a3", "4.e3", "4.Qc2", "4.Bg5"], 2, "4.Qc2 protects c3 with the queen and prepares e4."),
      quiz("Mistake", "When should Black avoid ...Bxc3?", ["When it creates no useful target or gain", "Whenever White plays a3", "After castling", "When c3 is occupied"], 0, "The bishop pair should not be surrendered without structural or tactical compensation."),
    ],
  },
  {
    id: "grunfeld",
    name: "Grünfeld Defense",
    side: "Black",
    difficulty: "Advanced",
    style: ["Dynamic", "Hypermodern", "Tactical"],
    startingMoves: "1.d4 Nf6 2.c4 g6 3.Nc3 d5",
    character: "Direct piece pressure against a deliberately large center",
    skillLevel: "Intermediate to advanced",
    glyph: "♝",
    intro: "The Grünfeld gives White an imposing pawn center, then attacks it immediately with the g7 bishop, ...c5, and active pieces. Unlike slower hypermodern systems, Black challenges d4 on move three and relies on exact activity rather than a closed shell.",
    objectives: [
      "Force White to define the center early",
      "Aim the g7 bishop at d4 and b2",
      "Use ...c5 as the main pressure lever",
      "Trade central defenders before attacking the pawns",
      "Value piece activity over holding territory",
    ],
    plans: {
      white: [
        "Use e4 to build a mobile center after exchanging on d5.",
        "Develop quickly enough to support d4 before Black's ...c5 pressure.",
        "Advance d5 only when it gains a concrete tempo or space advantage.",
        "Use the central pawns to restrict Black's pieces.",
      ],
      black: [
        "Fianchetto Bg7 and strike d4 with ...c5.",
        "Exchange Nc3 when it strengthens pressure on d4.",
        "Attack the center with pieces from c6, g7, and a5.",
        "Open files before White can use the space advantage for an attack.",
      ],
    },
    keySquares: [
      { square: "d4", label: "The center's main target" },
      { square: "c5", label: "Black's thematic undermining break" },
      { square: "g7", label: "The bishop's pressure station" },
      { square: "c3", label: "A key defender Black often exchanges" },
    ],
    pawnStructure: "In the Exchange Variation, White may own e4 and d4 while Black has no central pawn. Black attacks that impressive center with ...c5, Bg7, and piece exchanges until it becomes mobile or vulnerable.",
    mistakes: [
      "Allowing White to keep the center without playing ...c5",
      "Trading pieces that were needed to pressure d4",
      "Playing for pawn wins while the center can advance with tempo",
      "White expanding before securing the king and d4",
    ],
    memoryTip: "Give White the center only if every piece is ready to attack it.",
    mainLine: line(
      "Exchange Variation",
      GRUNFELD_START,
      [
        ply("c4", "d5", "cxd5", "White exchanges and asks Black how the center will be recovered."),
        ply("f6", "d5", "Nxd5", "Black recaptures with a piece, keeping the g7 bishop's diagonal open."),
        ply("e2", "e4", "e4", "White drives the knight and constructs the famous mobile pawn center."),
        ply("d5", "c3", "Nxc3", "Black removes a defender so the center will be harder to maintain."),
        ply("b2", "c3", "bxc3", "White supports d4 with a pawn and opens the b-file, accepting a structural target."),
        ply("f8", "g7", "Bg7", "The bishop immediately attacks d4 along the long diagonal."),
        ply("g1", "f3", "Nf3", "White develops another defender of d4 and prepares castling."),
        ply("c7", "c5", "c5", "Black hits the base of the center before White can advance comfortably."),
      ],
    ),
    variations: [
      line(
        "Russian Variation",
        GRUNFELD_START,
        [
          ply("g1", "f3", "Nf3", "White develops before clarifying the central tension."),
          ply("f8", "g7", "Bg7", "Black completes the fianchetto and adds pressure to d4."),
          ply("d1", "b3", "Qb3", "White protects d4 and attacks b7, making the central capture more concrete."),
          ply("d5", "c4", "dxc4", "Black accepts the temporary pawn, drawing the queen into recapture."),
          ply("b3", "c4", "Qxc4", "White regains the pawn and centralizes the queen."),
          ply("e8", "g8", "O-O", "Black secures the king and plans ...Na6 or ...c6 against the queen."),
        ],
      ),
      line(
        "Classical Bf4 Variation",
        GRUNFELD_START,
        [
          ply("g1", "f3", "Nf3", "White develops and reinforces d4."),
          ply("f8", "g7", "Bg7", "Black activates the long diagonal."),
          ply("c1", "f4", "Bf4", "White develops outside the pawn chain and adds support to e5."),
          ply("e8", "g8", "O-O", "Black castles before challenging the center."),
          ply("e2", "e3", "e3", "White stabilizes d4 and opens the f1 bishop."),
          ply("c7", "c5", "c5", "Black immediately attacks the center's d4 base."),
        ],
      ),
      line(
        "Fianchetto Variation",
        GRUNFELD_START,
        [
          ply("g2", "g3", "g3", "White prepares a matching fianchetto and reinforces the dark squares."),
          ply("f8", "g7", "Bg7", "Black completes the opening's key bishop development."),
          ply("f1", "g2", "Bg2", "White points a bishop toward d5 and the queenside."),
          ply("d5", "c4", "dxc4", "Black clarifies the center before White can recapture with a piece."),
          ply("g1", "f3", "Nf3", "White develops and prepares to recover c4 with the queen or knight."),
          ply("e8", "g8", "O-O", "Black secures the king and keeps the extra pawn only temporarily."),
          ply("e1", "g1", "O-O", "White finishes development before recovering the pawn."),
        ],
      ),
      line(
        "Accelerated Russian Variation",
        GRUNFELD_START,
        [
          ply("d1", "b3", "Qb3", "White immediately pressures b7 and d5 before developing the knight."),
          ply("d5", "c4", "dxc4", "Black removes the c4 pawn and opens the diagonal toward the queen."),
          ply("b3", "c4", "Qxc4", "White recaptures and places the queen actively in the center."),
          ply("f8", "g7", "Bg7", "Black develops with tempo along the diagonal toward c3."),
          ply("e2", "e4", "e4", "White builds a broad center while the queen supports d4."),
          ply("e8", "g8", "O-O", "Black castles and prepares to attack the center with ...c6 or ...Na6."),
        ],
      ),
      line(
        "Neo-Grünfeld Fianchetto",
        GRUNFELD_START.slice(0, 4),
        [
          ply("g2", "g3", "g3", "White chooses a fianchetto before developing Nc3, reducing tactical pressure on that knight."),
          ply("d7", "d5", "d5", "Black still challenges the center immediately."),
          ply("f1", "g2", "Bg2", "White develops onto the long diagonal and pressures d5."),
          ply("f8", "g7", "Bg7", "Black mirrors the fianchetto and targets d4."),
          ply("c4", "d5", "cxd5", "White clarifies the center before Black can reinforce it."),
          ply("f6", "d5", "Nxd5", "Black recaptures with active piece placement."),
        ],
      ),
    ],
    quiz: [
      quiz("Recognition", "Which move defines the Grünfeld after 1.d4 Nf6 2.c4 g6 3.Nc3?", ["...Bg7", "...d5", "...c5", "...e6"], 1, "3...d5 challenges the center immediately."),
      quiz("Concept", "Why does Black permit White's e4–d4 center?", ["To attack it with pieces and ...c5", "To force a draw", "To win the a-pawn", "To avoid development"], 0, "The center becomes a target for Bg7, ...c5, and tactical exchanges."),
      quiz("Exchange", "Why does Black play ...Nxc3 before ...Bg7?", ["To win a queen", "To remove a central defender", "To prevent castling", "To trap a rook"], 1, "Removing Nc3 makes the d4 center harder to maintain."),
      quiz("Break", "What is Black's signature pawn break?", ["...f5", "...b5", "...c5", "...h5"], 2, "...c5 attacks the base of White's pawn center."),
      quiz("Mistake", "What if Black delays pressure on d4?", ["White may consolidate the space advantage", "Black wins e4", "White loses castling rights", "The g7 bishop becomes a rook"], 0, "Without active counterplay, the center is simply an advantage for White."),
    ],
  },
  {
    id: "dutch",
    name: "Dutch Defense",
    side: "Black",
    difficulty: "Intermediate",
    style: ["Aggressive", "Dynamic", "Strategic"],
    startingMoves: "1.d4 f5",
    character: "An unbalanced fight for e4 with kingside ambitions",
    skillLevel: "Intermediate",
    glyph: "♟",
    intro: "The Dutch controls e4 with the f-pawn and creates immediate imbalance. Black gains attacking chances and a clear strategic goal, but the advance weakens the king, so development and structure must support the ambition.",
    objectives: [
      "Prevent White from occupying e4 easily",
      "Choose a Leningrad, Classical, or Stonewall structure",
      "Build a kingside attack without neglecting the center",
      "Use ...e5 or ...c5 as a freeing break",
      "Keep the weakened dark squares around the king under control",
    ],
    plans: {
      white: [
        "Fianchetto Bg2 to pressure the queenside and e4.",
        "Use e4 breaks when Black's center is not ready.",
        "Target the e6 and e5 dark squares.",
        "Open the center before Black's kingside attack gathers force.",
      ],
      black: [
        "In the Leningrad, fianchetto Bg7 and prepare ...e5.",
        "In the Stonewall, control e4 with pawns and place Ne4.",
        "Use Qe8–h5 or kingside pawn expansion only after castling.",
        "Challenge White's center with ...c5 when ...e5 is unavailable.",
      ],
    },
    keySquares: [
      { square: "e4", label: "The Dutch pawn's central control point" },
      { square: "e5", label: "Black's freeing advance in many systems" },
      { square: "g7", label: "The Leningrad bishop's post" },
      { square: "e6", label: "A potential dark-square weakness" },
    ],
    pawnStructure: "Leningrad structures use f5, g6, and d6; Stonewall structures add e6, d5, and c6. Both control e4, but they leave different dark-square and bishop problems.",
    mistakes: [
      "Starting a kingside attack before castling",
      "Playing ...f5 and then allowing e4 without resistance",
      "Building a Stonewall while trapping the c8 bishop without a plan",
      "Ignoring the weakened e6–g8 diagonal",
    ],
    memoryTip: "...f5 buys e4 control; repay the king weakness with fast, purposeful development.",
    mainLine: line(
      "Leningrad Dutch",
      DUTCH_START,
      [
        ply("g2", "g3", "g3", "White prepares Bg2 to pressure the long diagonal and e4."),
        ply("g8", "f6", "Nf6", "Black develops while adding another defender to e4."),
        ply("f1", "g2", "Bg2", "White completes the fianchetto and points at b7."),
        ply("g7", "g6", "g6", "Black prepares its own fianchetto, the defining Leningrad setup."),
        ply("g1", "f3", "Nf3", "White controls e5 and prepares castling."),
        ply("f8", "g7", "Bg7", "Black activates the bishop behind the f5 pawn and supports ...e5."),
        ply("e1", "g1", "O-O", "White secures the king before opening the center."),
        ply("e8", "g8", "O-O", "Black makes the king safe and connects the rook to the f-file."),
        ply("c2", "c4", "c4", "White increases queenside space and pressure on d5."),
        ply("d7", "d6", "d6", "Black prepares ...e5, the central break that activates the Leningrad."),
      ],
    ),
    variations: [
      line(
        "Classical Dutch",
        DUTCH_START,
        [
          ply("c2", "c4", "c4", "White takes queenside space and controls d5."),
          ply("g8", "f6", "Nf6", "Black reinforces e4 and develops."),
          ply("b1", "c3", "Nc3", "White develops toward e4 and d5."),
          ply("e7", "e6", "e6", "Black supports f5 and opens the f8 bishop."),
          ply("g1", "f3", "Nf3", "White adds central control and prepares castling."),
          ply("f8", "e7", "Be7", "Black chooses classical development and prepares king safety."),
          ply("g2", "g3", "g3", "White prepares the standard kingside fianchetto."),
          ply("e8", "g8", "O-O", "Black castles before seeking ...d6 and ...e5."),
        ],
      ),
      line(
        "Stonewall Dutch",
        DUTCH_START,
        [
          ply("c2", "c4", "c4", "White controls d5 and gains queenside space."),
          ply("g8", "f6", "Nf6", "Black reinforces e4 and develops."),
          ply("b1", "c3", "Nc3", "White prepares e4 and develops naturally."),
          ply("e7", "e6", "e6", "Black builds the base of the Stonewall chain."),
          ply("g1", "f3", "Nf3", "White adds control of e5."),
          ply("d7", "d5", "d5", "Black fixes the Stonewall pawns and secures the e4 outpost."),
          ply("c1", "f4", "Bf4", "White develops outside the pawn chain and targets c7."),
          ply("c7", "c6", "c6", "Black completes the wall and makes d5 hard to undermine."),
        ],
      ),
      line(
        "Staunton Gambit",
        DUTCH_START,
        [
          ply("e2", "e4", "e4", "White offers a pawn to exploit Black's delayed development and weakened king."),
          ply("f5", "e4", "fxe4", "Black accepts and gains a pawn, but opens the f-file and central lines."),
          ply("b1", "c3", "Nc3", "White develops with tempo against the advanced e4 pawn."),
          ply("g8", "f6", "Nf6", "Black protects e4 while bringing out a kingside piece."),
          ply("c1", "g5", "Bg5", "White pins the defender and increases pressure on e4."),
          ply("d7", "d5", "d5", "Black supports the extra pawn with a central foothold."),
          ply("f2", "f3", "f3", "White attacks the pawn chain and opens the f-file further."),
          ply("e4", "f3", "exf3", "Black releases the pawn to disturb White's kingside structure."),
        ],
      ),
      line(
        "Hopton Attack",
        DUTCH_START,
        [
          ply("c1", "g5", "Bg5", "White immediately questions the kingside and makes ...Nf6 less comfortable."),
          ply("h7", "h6", "h6", "Black asks the bishop to choose between retreat and exchange."),
          ply("g5", "h4", "Bh4", "White keeps the bishop on the h4–d8 diagonal."),
          ply("g7", "g5", "g5", "Black gains space and chases the bishop, at the cost of more king weakness."),
          ply("e2", "e3", "e3", "White opens a retreat to g3 and supports the center."),
          ply("g8", "f6", "Nf6", "Black finally develops and controls e4."),
          ply("h4", "g3", "Bg3", "White preserves the bishop and keeps pressure on c7."),
        ],
      ),
      line(
        "Ilyin–Zhenevsky System",
        DUTCH_START,
        [
          ply("c2", "c4", "c4", "White takes queenside space."),
          ply("g8", "f6", "Nf6", "Black reinforces e4."),
          ply("b1", "c3", "Nc3", "White develops and supports e4."),
          ply("e7", "e6", "e6", "Black opens the f8 bishop and supports the f-pawn."),
          ply("g1", "f3", "Nf3", "White completes natural central development."),
          ply("f8", "e7", "Be7", "Black prepares castling without fianchettoing."),
          ply("e2", "e3", "e3", "White opens the f1 bishop and stabilizes d4."),
          ply("e8", "g8", "O-O", "Black secures the king before building ...d6 and ...e5."),
          ply("f1", "d3", "Bd3", "White develops toward h7 and prepares castling."),
          ply("d7", "d6", "d6", "Black supports the thematic ...e5 central break."),
        ],
      ),
    ],
    quiz: [
      quiz("Recognition", "Which first move defines the Dutch Defense?", ["1...f5", "1...d5", "1...Nf6", "1...e6"], 0, "1...f5 controls e4 and creates immediate imbalance."),
      quiz("Tradeoff", "What does ...f5 gain and weaken?", ["d5 control and the queen", "e4 control and the king", "a-file control and a rook", "a pawn and the bishop pair"], 1, "The f-pawn controls e4 but no longer shields the king."),
      quiz("Leningrad", "Which development defines the Leningrad setup?", ["...b6 and ...Bb7", "...g6 and ...Bg7", "...c6 and ...d5", "...Nc6 and ...e5"], 1, "The kingside fianchetto distinguishes the Leningrad Dutch."),
      quiz("Stonewall", "Which square is the Stonewall built to control?", ["a4", "c8", "e4", "h6"], 2, "Pawns on f5, e6, d5, and c6 make e4 a powerful outpost."),
      quiz("Mistake", "When is a kingside attack most premature?", ["Before Black castles and develops", "After ...e5", "When White plays c4", "After a queen trade"], 0, "Black's own king must be safe before more lines are opened."),
    ],
  },
  {
    id: "london",
    name: "London System",
    side: "White",
    difficulty: "Beginner",
    style: ["Solid", "Positional", "Beginner Friendly"],
    startingMoves: "1.d4 d5 2.Nf3 Nf6 3.Bf4",
    character: "A dependable setup with clear piece placement",
    skillLevel: "Beginner to intermediate",
    glyph: "♗",
    intro: "The London develops the dark-squared bishop before e3 and builds a compact d4–e3–c3 structure. Its move order is reusable, but the opening becomes much stronger when White adapts to ...c5, ...Qb6, and kingside fianchetto setups rather than playing automatically.",
    objectives: [
      "Develop Bf4 before playing e3",
      "Support d4 with Nf3, e3, and c3",
      "Complete Bd3, Nbd2, and castling efficiently",
      "Use Ne5 as a central outpost",
      "React accurately to ...c5 and ...Qb6 pressure",
    ],
    plans: {
      white: [
        "Build the triangle d4–e3–c3 and place Nbd2.",
        "Use Bd3 and Ne5 to create kingside pressure.",
        "Meet ...Qb6 with Qb3, Qc1, or a timely c4 according to the position.",
        "Break with e4 only when development supports it.",
      ],
      black: [
        "Challenge d4 early with ...c5.",
        "Use ...Qb6 to pressure b2 and d4.",
        "Exchange the active f4 bishop when it helps central control.",
        "Avoid allowing an effortless Ne5–Bd3 kingside setup.",
      ],
    },
    keySquares: [
      { square: "f4", label: "The London bishop's active home" },
      { square: "e5", label: "White's ideal knight outpost" },
      { square: "d4", label: "The structure's central anchor" },
      { square: "b2", label: "Black's ...Qb6 pressure point" },
    ],
    pawnStructure: "White commonly places pawns on d4, e3, and c3. The structure is hard to break but can become passive unless White uses Ne5, c4, or e4 at the right moment.",
    mistakes: [
      "Playing the same setup without reacting to Black's threats",
      "Ignoring b2 after ...Qb6",
      "Trading the f4 bishop without a reason",
      "Keeping every pawn fixed and giving Black easy equality",
    ],
    memoryTip: "Bishop outside, triangle inside—then find the active break instead of stopping the setup there.",
    mainLine: line(
      "Classical London",
      LONDON_START,
      [
        ply("e7", "e6", "e6", "Black supports d5 and opens the f8 bishop."),
        ply("e2", "e3", "e3", "White secures d4 and opens the light-squared bishop after Bf4 is active."),
        ply("f8", "d6", "Bd6", "Black challenges the important London bishop and speeds castling."),
        ply("f4", "g3", "Bg3", "White preserves the bishop while inviting a useful h-pawn recapture if exchanged."),
        ply("e8", "g8", "O-O", "Black completes king safety before challenging the center."),
        ply("f1", "d3", "Bd3", "White aims at h7 and prepares kingside castling."),
        ply("c7", "c5", "c5", "Black attacks d4 before White can settle into the ideal setup."),
      ],
    ),
    variations: [
      line(
        "Jobava London",
        [
          ply("d2", "d4", "d4", "White claims the center."),
          ply("g8", "f6", "Nf6", "Black controls e4."),
          ply("b1", "c3", "Nc3", "White develops the queen's knight aggressively instead of using c3."),
          ply("d7", "d5", "d5", "Black establishes central space."),
          ply("c1", "f4", "Bf4", "White completes the Jobava setup and eyes c7."),
          ply("c8", "f5", "Bf5", "Black develops actively and contests the same diagonal."),
          ply("e2", "e3", "e3", "White supports d4 and opens the f1 bishop."),
          ply("e7", "e6", "e6", "Black builds a sound center and opens the f8 bishop."),
          ply("c3", "b5", "Nb5", "White exploits the knight's placement to create pressure on c7."),
        ],
      ),
      line(
        "Barry Attack",
        [
          ply("d2", "d4", "d4", "White takes central space."),
          ply("g8", "f6", "Nf6", "Black develops flexibly."),
          ply("g1", "f3", "Nf3", "White develops and controls e5."),
          ply("g7", "g6", "g6", "Black prepares a kingside fianchetto."),
          ply("b1", "c3", "Nc3", "White develops more aggressively than in the standard London."),
          ply("d7", "d5", "d5", "Black occupies the center."),
          ply("c1", "f4", "Bf4", "White completes the Barry setup and prepares e3 or Qd2."),
          ply("f8", "g7", "Bg7", "Black activates the bishop toward d4."),
          ply("e2", "e3", "e3", "White reinforces d4 and prepares a kingside attack."),
          ply("e8", "g8", "O-O", "Black secures the king before White's h-pawn can advance."),
        ],
      ),
      line(
        "Early ...Qb6 Challenge",
        LONDON_START.slice(0, 2),
        [
          ply("g1", "f3", "Nf3", "White develops and protects d4."),
          ply("g8", "f6", "Nf6", "Black develops naturally."),
          ply("c1", "f4", "Bf4", "White activates the London bishop."),
          ply("c7", "c5", "c5", "Black attacks d4 before White plays c3."),
          ply("e2", "e3", "e3", "White supports d4 and opens the f1 bishop."),
          ply("b8", "c6", "Nc6", "Black adds another attacker to d4."),
          ply("c2", "c3", "c3", "White stabilizes the central anchor."),
          ply("d8", "b6", "Qb6", "Black creates a double target on b2 and d4."),
          ply("d1", "b3", "Qb3", "White offers a queen trade while protecting both pressured pawns."),
        ],
      ),
      line(
        "Early ...c5 Structure",
        [
          ply("d2", "d4", "d4", "White claims central space."),
          ply("g8", "f6", "Nf6", "Black develops without committing the d-pawn."),
          ply("g1", "f3", "Nf3", "White controls e5 and supports d4."),
          ply("e7", "e6", "e6", "Black prepares ...c5 and opens the f8 bishop."),
          ply("c1", "f4", "Bf4", "White develops the bishop before playing e3."),
          ply("c7", "c5", "c5", "Black attacks d4 immediately and prevents a purely automatic setup."),
          ply("e2", "e3", "e3", "White keeps the center supported and opens the bishop."),
          ply("b8", "c6", "Nc6", "Black increases pressure on d4 and e5."),
          ply("c2", "c3", "c3", "White completes the triangle and makes d4 resilient."),
          ply("d7", "d5", "d5", "Black fixes a classical central structure and contests e4."),
        ],
      ),
      line(
        "King's Indian Setup",
        [
          ply("d2", "d4", "d4", "White takes central space."),
          ply("g8", "f6", "Nf6", "Black controls e4."),
          ply("g1", "f3", "Nf3", "White develops flexibly."),
          ply("g7", "g6", "g6", "Black prepares the kingside fianchetto."),
          ply("c1", "f4", "Bf4", "White places the bishop outside the pawn chain."),
          ply("f8", "g7", "Bg7", "Black attacks d4 along the long diagonal."),
          ply("e2", "e3", "e3", "White supports d4 and opens the f1 bishop."),
          ply("e8", "g8", "O-O", "Black makes the king safe."),
          ply("f1", "e2", "Be2", "White chooses a restrained development square that avoids ...Nh5 tempo."),
          ply("d7", "d6", "d6", "Black prepares ...e5 to challenge the center."),
          ply("e1", "g1", "O-O", "White completes king safety before the center changes."),
        ],
      ),
    ],
    quiz: [
      quiz("Recognition", "Which bishop move is the London System's signature?", ["Bc4", "Bb5", "Bf4", "Bg5"], 2, "Bf4 develops the bishop before e3 closes its original diagonal."),
      quiz("Structure", "Which pawn triangle supports White's center?", ["d4–e3–c3", "e4–f3–g3", "c4–d3–e2", "a3–b4–c5"], 0, "The compact d4–e3–c3 triangle is the London's structural base."),
      quiz("Outpost", "Which square is often ideal for White's knight?", ["a1", "e5", "h2", "b8"], 1, "Ne5 supports kingside play and central control."),
      quiz("Defense", "What does ...Qb6 usually attack?", ["h2 and f4", "b2 and d4", "a2 and e2", "c3 and g3"], 1, "The queen creates two queenside and central targets at once."),
      quiz("Mistake", "Why is playing the London setup automatically a problem?", ["The moves are illegal", "Black's ...c5 or ...Qb6 may demand a response", "Bf4 loses a bishop", "White cannot castle"], 1, "A sound setup still requires attention to the opponent's active plan."),
    ],
  },
  {
    id: "catalan",
    name: "Catalan Opening",
    side: "White",
    difficulty: "Advanced",
    style: ["Positional", "Strategic", "Fianchetto"],
    startingMoves: "1.d4 Nf6 2.c4 e6 3.g3",
    character: "Long-term queenside pressure with a flexible center",
    skillLevel: "Intermediate to advanced",
    glyph: "♗",
    intro: "The Catalan combines Queen's Gambit pressure with a kingside fianchetto. White may sacrifice or temporarily leave the c4 pawn to activate Bg2 against Black's queenside, making the opening a lesson in long-term piece activity and positional compensation.",
    objectives: [
      "Fianchetto Bg2 toward the queenside",
      "Pressure d5 without blocking the bishop",
      "Recover c4 only when it improves piece placement",
      "Use the open c- and d-files for long-term pressure",
      "Turn the bishop's diagonal into a queenside endgame advantage",
    ],
    plans: {
      white: [
        "Complete Bg2, Nf3, and castling before recovering c4.",
        "Use Qc2 or Qa4+ to regain the gambit pawn efficiently.",
        "Pressure b7 and c6 with the long bishop.",
        "Open the center when Black's queenside is underdeveloped.",
      ],
      black: [
        "Choose an Open Catalan with ...dxc4 or a Closed Catalan with ...Be7.",
        "If holding c4, support it only when the cost in development is acceptable.",
        "Use ...c5 to challenge White's central grip.",
        "Block the g2 bishop with ...Bd5 or active piece play, not passive pawns alone.",
      ],
    },
    keySquares: [
      { square: "g2", label: "The Catalan bishop's home" },
      { square: "c4", label: "The pawn Black may capture temporarily" },
      { square: "d5", label: "The central pressure point" },
      { square: "b7", label: "The long diagonal's queenside target" },
    ],
    pawnStructure: "White usually keeps d4 with a fianchettoed bishop and may lose c4 temporarily. Open Catalans feature an absent c-pawn and active lines; Closed Catalans preserve the d5 chain and lead to slow pressure.",
    mistakes: [
      "Rushing to recover c4 at the cost of development",
      "Allowing the g2 bishop to stare into a permanently closed center",
      "Treating the extra pawn in the Open Catalan as safely won",
      "Opening the center before the king is secure",
    ],
    memoryTip: "The c4 pawn may be temporary; the g2 bishop's pressure is the lasting asset.",
    mainLine: line(
      "Open Catalan",
      CATALAN_START,
      [
        ply("d7", "d5", "d5", "Black builds a classical center and accepts pressure along the long diagonal."),
        ply("f1", "g2", "Bg2", "White completes the defining fianchetto and attacks d5 and b7."),
        ply("d5", "c4", "dxc4", "Black takes the c-pawn, gaining material but yielding central tension and time."),
        ply("g1", "f3", "Nf3", "White develops instead of rushing to recover the pawn, increasing central control."),
        ply("f8", "b4", "Bb4+", "Black develops with tempo and interferes with White's easy recapture."),
        ply("c1", "d2", "Bd2", "White blocks the check while offering a bishop exchange that helps development."),
        ply("a7", "a5", "a5", "Black supports the queenside space and makes a future ...b5 pawn hold more stable."),
      ],
    ),
    variations: [
      line(
        "Closed Catalan",
        CATALAN_START,
        [
          ply("d7", "d5", "d5", "Black forms a classical center and keeps the c4 tension unresolved."),
          ply("f1", "g2", "Bg2", "White places the bishop on the long diagonal."),
          ply("f8", "e7", "Be7", "Black declines the pawn capture and prepares simple castling."),
          ply("g1", "f3", "Nf3", "White increases pressure on d5 and prepares king safety."),
          ply("e8", "g8", "O-O", "Black secures the king behind the closed center."),
          ply("e1", "g1", "O-O", "White completes development before increasing central pressure."),
          ply("b8", "d7", "Nbd7", "Black reinforces e5 and c5 while keeping the c-pawn flexible."),
        ],
      ),
      line(
        "Classical Open Catalan",
        CATALAN_START,
        [
          ply("d7", "d5", "d5", "Black occupies the center."),
          ply("f1", "g2", "Bg2", "White activates the long diagonal."),
          ply("d5", "c4", "dxc4", "Black accepts the c4 pawn and challenges White's compensation."),
          ply("g1", "f3", "Nf3", "White develops with pressure on e5 and d4."),
          ply("f8", "e7", "Be7", "Black prioritizes castling rather than trying to hold c4 immediately."),
          ply("e1", "g1", "O-O", "White secures the king and activates the rook."),
          ply("e8", "g8", "O-O", "Black completes king safety."),
          ply("d1", "c2", "Qc2", "White attacks c4 and aligns the queen with h7."),
        ],
      ),
      line(
        "Open Catalan with Qa4+",
        CATALAN_START,
        [
          ply("d7", "d5", "d5", "Black establishes the central pawn."),
          ply("f1", "g2", "Bg2", "White develops the Catalan bishop."),
          ply("d5", "c4", "dxc4", "Black takes the c-pawn and temporarily gains material."),
          ply("d1", "a4", "Qa4+", "White recovers time with check and targets c4 along the fourth rank."),
          ply("b8", "d7", "Nbd7", "Black blocks the check while developing and supporting c5."),
          ply("a4", "c4", "Qxc4", "White regains the pawn without losing a separate development tempo."),
          ply("c7", "c5", "c5", "Black challenges d4 and activates the queenside before White consolidates."),
        ],
      ),
      line(
        "Bogo-Catalan Check",
        CATALAN_START,
        [
          ply("f8", "b4", "Bb4+", "Black uses a check to influence White's development before playing ...d5."),
          ply("c1", "d2", "Bd2", "White blocks while inviting a favorable bishop exchange."),
          ply("b4", "e7", "Be7", "Black keeps the bishop and avoids helping White develop the queen."),
          ply("f1", "g2", "Bg2", "White completes the fianchetto and claims the long diagonal."),
          ply("d7", "d5", "d5", "Black establishes a solid center under the bishop's pressure."),
          ply("g1", "f3", "Nf3", "White adds pressure to d5 and prepares castling."),
        ],
      ),
      line(
        "Delayed Open Catalan",
        CATALAN_START,
        [
          ply("d7", "d5", "d5", "Black occupies the center and leaves the c-pawn tension intact."),
          ply("g1", "f3", "Nf3", "White develops before revealing the bishop, keeping options flexible."),
          ply("f8", "e7", "Be7", "Black prepares castling in a closed structure."),
          ply("f1", "g2", "Bg2", "White completes the fianchetto and increases pressure on d5."),
          ply("e8", "g8", "O-O", "Black secures the king."),
          ply("e1", "g1", "O-O", "White also makes the king safe."),
          ply("d5", "c4", "dxc4", "Black waits until both sides are developed before changing to an Open Catalan."),
          ply("d1", "c2", "Qc2", "White attacks c4 and prepares to recover it without moving a developed piece twice."),
        ],
      ),
    ],
    quiz: [
      quiz("Recognition", "Which move gives the Queen's Gambit structure a Catalan character?", ["g3", "a3", "f4", "b3 only"], 0, "g3 prepares Bg2, the opening's defining long-range piece."),
      quiz("Open vs closed", "What makes the Catalan 'Open'?", ["White plays e4", "Black captures c4", "Queens are traded", "The f-pawn advances"], 1, "...dxc4 releases the central tension and creates open lines."),
      quiz("Compensation", "Why need White not recover c4 immediately?", ["The pawn cannot move", "Development and bishop pressure can be worth more tempi", "White is already a rook ahead", "Black must return it by rule"], 1, "The Catalan is built on long-term activity rather than a rushed pawn chase."),
      quiz("Target", "Which queenside pawn sits on the g2 bishop's diagonal?", ["a7", "b7", "c7", "h7"], 1, "The bishop's ray through d5 and c6 often reaches b7."),
      quiz("Mistake", "What can go wrong if Black tries too hard to hold c4?", ["Black may fall behind in development", "Black loses castling rights automatically", "The queen disappears", "White promotes immediately"], 0, "Supporting the pawn with ...b5 and more moves can leave Black undeveloped under pressure."),
    ],
  },
];
