import { defineMove as m, defineQuizQuestion as q } from "./schema.js";

export const CORE_OPENINGS = [
  {
    id: "italian",
    name: "Italian Game",
    side: "White",
    difficulty: "Beginner",
    style: ["Tactical", "Classical", "Beginner Friendly"],
    startingMoves: "1.e4 e5 2.Nf3 Nc6 3.Bc4",
    character: "Open, active, and tactical",
    skillLevel: "Beginner to intermediate",
    glyph: "♗",
    intro:
      "The Italian Game develops quickly toward Black’s most sensitive early target, f7. It teaches classical opening habits: occupy the center, bring pieces out with purpose, and make the king safe before starting tactics.",
    objectives: [
      "Build a strong e4 center and develop with tempo",
      "Aim the light-squared bishop at the f7 pawn",
      "Castle early and connect the rooks",
      "Prepare c3 and d4 to open the center",
      "Use rapid development to create tactical threats",
    ],
    plans: {
      white: [
        "Play c3 followed by d4 to challenge the center.",
        "Castle kingside before opening central files.",
        "Use Re1 to reinforce e4 and support a central break.",
        "Watch for tactics on f7 when Black falls behind in development.",
      ],
      black: [
        "Develop the kingside quickly and castle.",
        "Counter White’s d4 break with ...exd4 or ...d6.",
        "Use ...Nf6 to attack e4 and force White to defend.",
        "Meet an early Ng5 with accurate central play.",
      ],
    },
    keySquares: [
      { square: "f7", label: "White’s early tactical target" },
      { square: "d4", label: "The main central break" },
      { square: "e5", label: "Black’s central anchor" },
      { square: "c4", label: "The bishop’s active diagonal" },
    ],
    pawnStructure:
      "White often builds pawns on e4 and c3, then plays d4. If the center opens, piece activity matters more than long-term pawn structure.",
    mistakes: [
      "Launching an attack on f7 before enough pieces are developed",
      "Playing d4 without checking whether the e4 pawn is protected",
      "Moving the bishop repeatedly while the kingside remains undeveloped",
      "Delaying castling in an opening that can become tactical quickly",
    ],
    memoryTip: "Point at f7, prepare d4, and get the king safe.",
    mainLine: {
      name: "Giuoco Piano — central break",
      moves: [
        m("e2", "e4", "1. e4", "White occupies the center and opens lines for the queen and bishop."),
        m("e7", "e5", "1... e5", "Black mirrors the central claim and frees both kingside pieces."),
        m("g1", "f3", "2. Nf3", "The knight develops with tempo by attacking the e5 pawn."),
        m("b8", "c6", "2... Nc6", "Black defends e5 while developing toward the center."),
        m("f1", "c4", "3. Bc4", "The signature Italian move develops the bishop toward the vulnerable f7 pawn."),
        m("f8", "c5", "3... Bc5", "Black develops actively and creates equal pressure on White’s f2 pawn."),
        m("c2", "c3", "4. c3", "White prepares the thematic d4 pawn break and gives the bishop a retreat square."),
        m("g8", "f6", "4... Nf6", "Black develops and immediately attacks White’s e4 pawn."),
        m("d2", "d4", "5. d4", "White challenges the center before Black can finish development."),
        m("e5", "d4", "5... exd4", "Black releases the central tension and temporarily opens the e-file."),
        m("c3", "d4", "6. cxd4", "White recaptures with the c-pawn and builds a broad central duo."),
        m("c5", "b4", "6... Bb4+", "Black checks while developing pressure and asks White to respond accurately."),
      ],
    },
    variations: [
      {
        name: "Two Knights Defense",
        moves: [
          m("e2", "e4", "1. e4", "White claims central space."),
          m("e7", "e5", "1... e5", "Black meets the center symmetrically."),
          m("g1", "f3", "2. Nf3", "White develops and attacks e5."),
          m("b8", "c6", "2... Nc6", "The e5 pawn is defended."),
          m("f1", "c4", "3. Bc4", "The bishop eyes f7."),
          m("g8", "f6", "3... Nf6", "Black chooses active counterplay against e4."),
          m("f3", "g5", "4. Ng5", "White increases pressure on f7, entering sharp theory."),
          m("d7", "d5", "4... d5", "Black must strike in the center rather than defend passively."),
          m("e4", "d5", "5. exd5", "White accepts the central confrontation."),
          m("c6", "a5", "5... Na5", "Black attacks the bishop and prepares active piece play."),
        ],
      },
      {
        name: "Evans Gambit",
        moves: [
          m("e2", "e4", "1. e4", "White opens the center."),
          m("e7", "e5", "1... e5", "Black claims equal space."),
          m("g1", "f3", "2. Nf3", "The knight attacks e5."),
          m("b8", "c6", "2... Nc6", "Black develops while defending."),
          m("f1", "c4", "3. Bc4", "White enters the Italian Game."),
          m("f8", "c5", "3... Bc5", "Black chooses the classical setup."),
          m("b2", "b4", "4. b4", "White offers a pawn to gain time and build a large center."),
          m("c5", "b4", "4... Bxb4", "Black accepts the gambit pawn."),
          m("c2", "c3", "5. c3", "White attacks the bishop and prepares d4 with tempo."),
          m("b4", "a5", "5... Ba5", "The bishop keeps the extra pawn while staying active."),
        ],
      },
      {
        name: "Giuoco Pianissimo",
        moves: [
          m("e2", "e4", "1. e4", "White claims the center."),
          m("e7", "e5", "1... e5", "Black mirrors."),
          m("g1", "f3", "2. Nf3", "Development with tempo."),
          m("b8", "c6", "2... Nc6", "Development and defense."),
          m("f1", "c4", "3. Bc4", "The Italian bishop takes its best diagonal."),
          m("f8", "c5", "3... Bc5", "Black develops symmetrically."),
          m("d2", "d3", "4. d3", "White supports e4 and chooses a slower buildup."),
          m("g8", "f6", "4... Nf6", "Black pressures e4."),
          m("e1", "g1", "5. O-O", "White makes the king safe before expanding."),
          m("d7", "d6", "5... d6", "Black stabilizes the center and frees the c8 bishop."),
        ],
      },
    ],
    quiz: [
      q("Recognition", "Which move defines the Italian Game after 1.e4 e5 2.Nf3 Nc6?", ["3.Bb5", "3.Bc4", "3.d4", "3.Nc3"], 1, "3.Bc4 is the defining move, placing the bishop on the f7 diagonal."),
      q("Strategy", "What is White’s main early target in the Italian Game?", ["a7", "c6", "f7", "h7"], 2, "The f7 pawn is defended only by the king at the start, so Bc4 creates immediate pressure."),
      q("Continuation", "After 3.Bc4 Bc5, which quiet move prepares the central break d4?", ["4.c3", "4.h3", "4.a3", "4.Qe2"], 0, "c3 supports d4 and is one of the Italian Game’s most important preparatory moves."),
      q("Understanding", "Why is early castling especially useful in the Italian Game?", ["It wins a pawn", "It prepares an open center safely", "It traps Black’s queen", "It prevents ...Nc6"], 1, "The center may open quickly after d4, so king safety lets White use tactical development confidently."),
      q("Mistake", "Which plan is most suspicious for White?", ["Developing Nf3", "Preparing c3 and d4", "Attacking f7 with only queen and bishop", "Castling kingside"], 2, "A premature two-piece attack on f7 is usually easy to meet and can leave White behind in development."),
    ],
  },
  {
    id: "ruy-lopez",
    name: "Ruy López",
    side: "White",
    difficulty: "Intermediate",
    style: ["Positional", "Strategic", "Classical"],
    startingMoves: "1.e4 e5 2.Nf3 Nc6 3.Bb5",
    character: "Strategic pressure with tactical undercurrents",
    skillLevel: "Intermediate",
    glyph: "♗",
    intro:
      "The Ruy López develops the bishop while questioning the knight that protects e5. White does not try to win the pawn immediately; instead, the opening builds long-term central pressure and a durable initiative.",
    objectives: [
      "Increase pressure on the e5 pawn through the c6 knight",
      "Castle quickly and support e4 with Re1",
      "Preserve the light-squared bishop when useful",
      "Prepare c3 and d4 for a central expansion",
      "Create a lasting space advantage without rushing",
    ],
    plans: {
      white: [
        "Retreat the bishop to b3 or c2 and keep its long diagonal.",
        "Use c3 and d4 to build a powerful center.",
        "Play Re1 before the center opens.",
        "Maneuver the queenside knight through d2-f1-g3 in slower lines.",
      ],
      black: [
        "Challenge the bishop with ...a6 and ...b5.",
        "Develop with ...Nf6 and ...Be7, then castle.",
        "Attack White’s center with ...d5 or ...c5 at the right moment.",
        "Use the queenside space gain without neglecting the king.",
      ],
    },
    keySquares: [
      { square: "e5", label: "The central pressure point" },
      { square: "c6", label: "The pinned defender" },
      { square: "d4", label: "White’s main central expansion" },
      { square: "b5", label: "The bishop’s defining post" },
    ],
    pawnStructure:
      "Closed-center Ruy López positions often feature White pawns on e4 and d4 against Black pawns on e5 and d6. Maneuvering precedes the eventual d4-d5 or ...d5 break.",
    mistakes: [
      "Assuming Bxc6 immediately wins the e5 pawn",
      "Allowing the b5 bishop to be trapped by ...a6 and ...b5",
      "Opening the center before castling",
      "Trading the light-squared bishop without a structural reason",
    ],
    memoryTip: "Pin the defender, secure the king, then build d4.",
    mainLine: {
      name: "Closed Ruy López",
      moves: [
        m("e2", "e4", "1. e4", "White occupies the center and opens development lines."),
        m("e7", "e5", "1... e5", "Black claims an equal share of the center."),
        m("g1", "f3", "2. Nf3", "White attacks e5 while developing."),
        m("b8", "c6", "2... Nc6", "The knight develops and protects e5."),
        m("f1", "b5", "3. Bb5", "White applies indirect pressure to e5 by pinning its knight defender."),
        m("a7", "a6", "3... a6", "Black asks the bishop to clarify its intentions."),
        m("b5", "a4", "4. Ba4", "White preserves the bishop and keeps the pin."),
        m("g8", "f6", "4... Nf6", "Black develops actively and attacks e4."),
        m("e1", "g1", "5. O-O", "White castles, making central action safer."),
        m("f8", "e7", "5... Be7", "Black prepares to castle and calmly breaks the pin."),
        m("f1", "e1", "6. Re1", "The rook reinforces e4 and prepares future central expansion."),
        m("b7", "b5", "6... b5", "Black gains queenside space and drives the bishop to its ideal retreat."),
        m("a4", "b3", "7. Bb3", "The bishop stays active on the a2–g8 diagonal."),
        m("d7", "d6", "7... d6", "Black secures e5 and develops the c8 bishop."),
      ],
    },
    variations: [
      {
        name: "Berlin Defense",
        moves: [
          m("e2", "e4", "1. e4", "White takes central space."),
          m("e7", "e5", "1... e5", "Black mirrors."),
          m("g1", "f3", "2. Nf3", "White attacks e5."),
          m("b8", "c6", "2... Nc6", "Black defends."),
          m("f1", "b5", "3. Bb5", "The Ruy López begins."),
          m("g8", "f6", "3... Nf6", "The Berlin develops immediately against e4."),
          m("e1", "g1", "4. O-O", "White makes the king safe."),
          m("f6", "e4", "4... Nxe4", "Black temporarily takes the center pawn, relying on tactics."),
          m("d2", "d4", "5. d4", "White strikes centrally and opens lines against the exposed knight."),
          m("e4", "d6", "5... Nd6", "The knight retreats while attacking the b5 bishop."),
        ],
      },
      {
        name: "Exchange Variation",
        moves: [
          m("e2", "e4", "1. e4", "White claims the center."),
          m("e7", "e5", "1... e5", "Black responds symmetrically."),
          m("g1", "f3", "2. Nf3", "Development with tempo."),
          m("b8", "c6", "2... Nc6", "Black defends e5."),
          m("f1", "b5", "3. Bb5", "White pins the knight."),
          m("a7", "a6", "3... a6", "The bishop is challenged."),
          m("b5", "c6", "4. Bxc6", "White exchanges bishop for knight to alter Black’s structure."),
          m("d7", "c6", "4... dxc6", "Black accepts doubled c-pawns but gains the bishop pair."),
          m("e1", "g1", "5. O-O", "White castles and can target e5 later."),
          m("f7", "f6", "5... f6", "Black securely defends e5, though development slows."),
        ],
      },
      {
        name: "Marshall Setup",
        moves: [
          m("e2", "e4", "1. e4", "White takes the center."), m("e7", "e5", "1... e5", "Black mirrors."),
          m("g1", "f3", "2. Nf3", "The knight develops."), m("b8", "c6", "2... Nc6", "e5 is defended."),
          m("f1", "b5", "3. Bb5", "Ruy López pressure."), m("a7", "a6", "3... a6", "Black gains space."),
          m("b5", "a4", "4. Ba4", "The bishop retreats."), m("g8", "f6", "4... Nf6", "Black attacks e4."),
          m("e1", "g1", "5. O-O", "White castles."), m("f8", "e7", "5... Be7", "Black prepares to castle."),
          m("f1", "e1", "6. Re1", "White supports e4."), m("b7", "b5", "6... b5", "The bishop is driven back."),
          m("a4", "b3", "7. Bb3", "The bishop keeps the diagonal."), m("e8", "g8", "7... O-O", "Black castles."),
          m("c2", "c3", "8. c3", "White prepares d4."), m("d7", "d5", "8... d5", "The Marshall idea: Black offers a pawn for rapid activity."),
        ],
      },
    ],
    quiz: [
      q("Recognition", "Which bishop move begins the Ruy López?", ["Bc4", "Bb5", "Bd3", "Be2"], 1, "Bb5 pins the c6 knight and creates indirect pressure on e5."),
      q("Understanding", "Does 3.Bb5 immediately threaten to win the e5 pawn?", ["Always", "No, Black can often recapture tactically", "Only if Black castles", "Only after ...a6"], 1, "After Bxc6 dxc6 Nxe5, Black often has Qd4, recovering the pawn through a fork."),
      q("Strategy", "What central break does White commonly prepare with c3?", ["c4", "f4", "d4", "b4"], 2, "c3 supports d4, building the classical Ruy López center."),
      q("Position", "What is Black’s usual purpose behind ...a6 and ...b5?", ["Trap the queen", "Gain space and question the bishop", "Attack f2", "Open the h-file"], 1, "The pawn duo expands on the queenside and forces the b5 bishop to choose a square."),
      q("Mistake", "Which assumption is a common beginner error?", ["Castling is useful", "Re1 supports e4", "Bxc6 automatically wins e5", "d4 can open the center"], 2, "The apparent pawn win often fails tactically, so the exchange must be evaluated carefully."),
    ],
  },
  {
    id: "sicilian",
    name: "Sicilian Defense",
    side: "Black",
    difficulty: "Intermediate",
    style: ["Dynamic", "Tactical", "Aggressive"],
    startingMoves: "1.e4 c5",
    character: "Asymmetrical and counterattacking",
    skillLevel: "Intermediate",
    glyph: "♞",
    intro:
      "The Sicilian Defense answers 1.e4 without copying White. Black controls d4 from the flank, accepts an asymmetrical structure, and often trades White’s kingside initiative for lasting queenside and c-file counterplay.",
    objectives: [
      "Challenge d4 with the c-pawn rather than mirror e4",
      "Create an asymmetrical pawn structure with winning chances",
      "Use the half-open c-file for queenside counterplay",
      "Develop flexibly before committing the central pawns",
      "Counterattack rather than defend passively",
    ],
    plans: {
      white: [
        "Open the center with d4 and use a lead in development.",
        "Build a kingside attack in many Open Sicilian structures.",
        "Control d5 and prevent Black’s freeing break.",
        "Choose quieter systems such as the Closed Sicilian or Alapin when preferred.",
      ],
      black: [
        "Exchange the c-pawn for White’s d-pawn to gain a central pawn majority.",
        "Place a rook on the half-open c-file.",
        "Seek ...d5 as the ideal freeing break.",
        "Generate queenside play while White often attacks the king.",
      ],
    },
    keySquares: [
      { square: "d4", label: "The square challenged by 1...c5" },
      { square: "d5", label: "Black’s freeing break" },
      { square: "c5", label: "The defining Sicilian pawn" },
      { square: "c8", label: "The future half-open file" },
    ],
    pawnStructure:
      "In the Open Sicilian, Black usually trades the c-pawn for White’s d-pawn. Black gains two central pawns against one, while White gains open lines and faster development.",
    mistakes: [
      "Playing ...e5 too early and leaving d5 permanently weak",
      "Ignoring development while hunting pawns on the queenside",
      "Castling into an attack without checking White’s setup",
      "Missing the freeing ...d5 break when it is available",
    ],
    memoryTip: "Trade c for d, use the c-file, and fight for ...d5.",
    mainLine: {
      name: "Open Sicilian — Najdorf structure",
      moves: [
        m("e2", "e4", "1. e4", "White claims the center."),
        m("c7", "c5", "1... c5", "Black attacks d4 from the flank and creates immediate imbalance."),
        m("g1", "f3", "2. Nf3", "White develops and prepares the d4 break."),
        m("d7", "d6", "2... d6", "Black controls e5 and prepares ...Nf6 without allowing e5."),
        m("d2", "d4", "3. d4", "White opens the center and offers a pawn exchange."),
        m("c5", "d4", "3... cxd4", "Black trades the flank pawn for White’s central d-pawn."),
        m("f3", "d4", "4. Nxd4", "White recaptures with development and centralizes the knight."),
        m("g8", "f6", "4... Nf6", "Black attacks e4 and develops naturally."),
        m("b1", "c3", "5. Nc3", "White protects e4 and controls d5."),
        m("a7", "a6", "5... a6", "The flexible Najdorf move prevents Nb5 and prepares queenside expansion."),
        m("c1", "e3", "6. Be3", "White develops and prepares Qd2 with possible queenside castling."),
        m("e7", "e6", "6... e6", "Black strengthens d5 and opens the dark-squared bishop."),
      ],
    },
    variations: [
      {
        name: "Open Sicilian",
        moves: [
          m("e2", "e4", "1. e4", "White takes the center."), m("c7", "c5", "1... c5", "The Sicilian begins."),
          m("g1", "f3", "2. Nf3", "White prepares d4."), m("b8", "c6", "2... Nc6", "Black develops and controls d4."),
          m("d2", "d4", "3. d4", "White opens the center."), m("c5", "d4", "3... cxd4", "Black exchanges c for d."),
          m("f3", "d4", "4. Nxd4", "The knight centralizes."), m("g8", "f6", "4... Nf6", "Black attacks e4."),
        ],
      },
      {
        name: "Closed Sicilian",
        moves: [
          m("e2", "e4", "1. e4", "White claims the center."), m("c7", "c5", "1... c5", "Black enters the Sicilian."),
          m("b1", "c3", "2. Nc3", "White keeps the center closed and develops."), m("b8", "c6", "2... Nc6", "Black increases control of d4."),
          m("g2", "g3", "3. g3", "White prepares a kingside fianchetto."), m("g7", "g6", "3... g6", "Black mirrors with flexible development."),
          m("f1", "g2", "4. Bg2", "White’s bishop controls the long diagonal."), m("f8", "g7", "4... Bg7", "Black completes the fianchetto."),
          m("d2", "d3", "5. d3", "White stabilizes e4 and plans a kingside expansion."), m("d7", "d6", "5... d6", "Black secures the center."),
        ],
      },
      {
        name: "Alapin Variation",
        moves: [
          m("e2", "e4", "1. e4", "White occupies the center."), m("c7", "c5", "1... c5", "Black chooses the Sicilian."),
          m("c2", "c3", "2. c3", "White prepares an immediate d4 pawn center."), m("g8", "f6", "2... Nf6", "Black attacks e4 before White completes the center."),
          m("e4", "e5", "3. e5", "White gains space and drives the knight."), m("f6", "d5", "3... Nd5", "The knight occupies a central blockading square."),
          m("d2", "d4", "4. d4", "White builds the desired pawn duo."), m("c5", "d4", "4... cxd4", "Black challenges the center immediately."),
          m("g1", "f3", "5. Nf3", "White develops and prepares to recapture."),
        ],
      },
    ],
    quiz: [
      q("Recognition", "Which opening begins after 1.e4 c5?", ["French Defense", "Sicilian Defense", "Caro-Kann Defense", "English Opening"], 1, "1...c5 defines the Sicilian Defense."),
      q("Strategy", "What central square does 1...c5 immediately influence?", ["e5", "f4", "d4", "b4"], 2, "The c-pawn controls d4, discouraging White from building an uncontested center."),
      q("Structure", "In an Open Sicilian, Black commonly exchanges the c-pawn for which pawn?", ["White’s e-pawn", "White’s d-pawn", "White’s b-pawn", "White’s f-pawn"], 1, "...cxd4 trades a flank pawn for a central pawn and opens the c-file."),
      q("Plan", "What is often Black’s ideal freeing pawn break?", ["...a5", "...f5", "...d5", "...h5"], 2, "A well-timed ...d5 challenges White’s center and often solves Black’s space problem."),
      q("Variation", "Which second move signals the Alapin Sicilian?", ["2.c3", "2.f4", "2.Bc4", "2.d3"], 0, "2.c3 prepares a broad d4 center and avoids much Open Sicilian theory."),
    ],
  },
  {
    id: "french",
    name: "French Defense",
    side: "Black",
    difficulty: "Intermediate",
    style: ["Strategic", "Counterattacking", "Positional"],
    startingMoves: "1.e4 e6 2.d4 d5",
    character: "Closed center and pawn-chain battles",
    skillLevel: "Intermediate",
    glyph: "♟",
    intro:
      "The French Defense lets White establish e4, then challenges it with ...d5. The center often closes, producing clear pawn chains: White attacks on the kingside while Black counterattacks the chain’s base on the queenside.",
    objectives: [
      "Challenge the e4 center immediately with ...d5",
      "Attack the base of White’s pawn chain with ...c5",
      "Create queenside counterplay in closed positions",
      "Time the freeing ...f6 break carefully",
      "Solve the c8 bishop’s development problem",
    ],
    plans: {
      white: [
        "Support e5 and gain kingside space with f4.",
        "Develop quickly before starting a kingside attack.",
        "Defend d4, the base of the pawn chain.",
        "Use c3 and Nf3 to reinforce the center.",
      ],
      black: [
        "Strike at d4 with ...c5 and ...Nc6.",
        "Pressure the center with ...Qb6.",
        "Use ...f6 to challenge the head of the pawn chain.",
        "Find a route for the c8 bishop via d7, a6, or b7.",
      ],
    },
    keySquares: [
      { square: "d4", label: "Base of White’s pawn chain" },
      { square: "e5", label: "Head of White’s pawn chain" },
      { square: "c5", label: "Black’s main counterbreak" },
      { square: "f6", label: "The second central challenge" },
    ],
    pawnStructure:
      "After e5, White’s chain often runs d4–e5 and points kingside. Black’s chain e6–d5 points queenside. Each side normally attacks where its chain points and pressures the opponent’s base.",
    mistakes: [
      "Playing passively and never challenging d4 with ...c5",
      "Locking in the c8 bishop without a development plan",
      "Playing ...f6 before the king and pieces are ready",
      "Grabbing d4 while falling behind in development",
    ],
    memoryTip: "Allow the center, lock it, then attack its base.",
    mainLine: {
      name: "Advance Variation",
      moves: [
        m("e2", "e4", "1. e4", "White takes central space."),
        m("e7", "e6", "1... e6", "Black prepares to challenge e4 with ...d5."),
        m("d2", "d4", "2. d4", "White builds the ideal central duo."),
        m("d7", "d5", "2... d5", "Black immediately challenges White’s e4 pawn."),
        m("e4", "e5", "3. e5", "White closes the center and gains kingside space."),
        m("c7", "c5", "3... c5", "Black attacks d4, the base of White’s pawn chain."),
        m("c2", "c3", "4. c3", "White reinforces d4 and stabilizes the chain."),
        m("b8", "c6", "4... Nc6", "Black develops another attacker against d4."),
        m("g1", "f3", "5. Nf3", "White supports d4 and develops toward the center."),
        m("d8", "b6", "5... Qb6", "Black adds pressure to d4 and b2 at the same time."),
        m("f1", "d3", "6. Bd3", "White develops actively and points toward h7."),
        m("c5", "d4", "6... cxd4", "Black clarifies the central tension before White can expand."),
      ],
    },
    variations: [
      {
        name: "Exchange Variation",
        moves: [
          m("e2", "e4", "1. e4", "White takes the center."), m("e7", "e6", "1... e6", "Black prepares a challenge."),
          m("d2", "d4", "2. d4", "White builds the pawn duo."), m("d7", "d5", "2... d5", "Black attacks e4."),
          m("e4", "d5", "3. exd5", "White releases the central tension."), m("e6", "d5", "3... exd5", "Black restores symmetry."),
          m("g1", "f3", "4. Nf3", "White develops."), m("g8", "f6", "4... Nf6", "Black develops symmetrically."),
        ],
      },
      {
        name: "Tarrasch Variation",
        moves: [
          m("e2", "e4", "1. e4", "White occupies e4."), m("e7", "e6", "1... e6", "Black prepares ...d5."),
          m("d2", "d4", "2. d4", "White takes more center."), m("d7", "d5", "2... d5", "Black challenges e4."),
          m("b1", "d2", "3. Nd2", "White supports e4 without blocking the c-pawn."), m("g8", "f6", "3... Nf6", "Black attacks e4."),
          m("e4", "e5", "4. e5", "White gains space."), m("f6", "d7", "4... Nfd7", "The knight reroutes to challenge e5."),
          m("f1", "d3", "5. Bd3", "White develops toward h7."), m("c7", "c5", "5... c5", "Black attacks d4."),
        ],
      },
    ],
    quiz: [
      q("Recognition", "Which moves define the French Defense?", ["1.e4 c5", "1.e4 e6 2.d4 d5", "1.e4 c6 2.d4 d5", "1.d4 Nf6"], 1, "The French begins with ...e6 and challenges e4 using ...d5."),
      q("Structure", "In the Advance French, which pawn is usually the base of White’s chain?", ["e5", "d4", "c3", "f2"], 1, "White’s d4 pawn supports e5, so Black attacks it with ...c5, ...Nc6, and often ...Qb6."),
      q("Plan", "What is Black’s thematic third move after 1.e4 e6 2.d4 d5 3.e5?", ["...a6", "...c5", "...f5", "...h6"], 1, "...c5 immediately attacks the base of White’s pawn chain."),
      q("Understanding", "What is Black’s traditional problem piece in the French?", ["The g8 knight", "The queen", "The c8 bishop", "The h8 rook"], 2, "The e6 pawn blocks the c8 bishop, so Black must plan its development carefully."),
      q("Mistake", "Why can an early ...f6 be risky?", ["It loses the c-pawn", "It weakens the king before development", "It blocks the queen", "It trades bishops"], 1, "...f6 is thematic, but premature use can expose Black’s king and open dangerous lines."),
    ],
  },
  {
    id: "caro-kann",
    name: "Caro-Kann Defense",
    side: "Black",
    difficulty: "Beginner",
    style: ["Solid", "Positional", "Beginner Friendly"],
    startingMoves: "1.e4 c6 2.d4 d5",
    character: "Sound structure and reliable development",
    skillLevel: "Beginner to intermediate",
    glyph: "♜",
    intro:
      "The Caro-Kann challenges e4 with ...d5 while keeping the c8 bishop free to develop. Black often accepts slightly less space in exchange for a healthy pawn structure and a dependable middlegame.",
    objectives: [
      "Challenge e4 with a supported ...d5 break",
      "Develop the light-squared bishop before playing ...e6",
      "Reach a sound endgame-friendly pawn structure",
      "Trade White’s advanced e-pawn when convenient",
      "Complete development without creating weaknesses",
    ],
    plans: {
      white: [
        "Use extra space to develop actively.",
        "Gain time against the bishop with Ng3 and h4-h5.",
        "Choose the Advance Variation for a space advantage.",
        "Avoid overextending before Black completes development.",
      ],
      black: [
        "Develop the c8 bishop to f5 or g4 before ...e6.",
        "Challenge White’s center with ...c5 or ...e5 later.",
        "Use the solid structure to simplify into favorable endings.",
        "Find safe squares for the f5 bishop when White advances h4-h5.",
      ],
    },
    keySquares: [
      { square: "d5", label: "Black’s central challenge" },
      { square: "f5", label: "The bishop’s active square" },
      { square: "e4", label: "The pawn Black wants to exchange" },
      { square: "c5", label: "A later freeing break" },
    ],
    pawnStructure:
      "After ...dxe4 and Nxe4, Black commonly plays ...Bf5 and ...e6. The c- and e-pawns remain compact, giving Black one of the healthiest structures among defenses to 1.e4.",
    mistakes: [
      "Playing ...e6 before developing the c8 bishop",
      "Allowing the f5 bishop to be trapped by h4-h5",
      "Remaining too passive after completing development",
      "Trading pieces automatically without considering activity",
    ],
    memoryTip: "Support ...d5, free the bishop, then build the shell.",
    mainLine: {
      name: "Classical Variation",
      moves: [
        m("e2", "e4", "1. e4", "White claims central space."),
        m("c7", "c6", "1... c6", "Black prepares ...d5 with pawn support."),
        m("d2", "d4", "2. d4", "White builds a broad center."),
        m("d7", "d5", "2... d5", "Black challenges e4 immediately."),
        m("b1", "c3", "3. Nc3", "White develops and reinforces e4."),
        m("d5", "e4", "3... dxe4", "Black releases the tension and asks White to recapture."),
        m("c3", "e4", "4. Nxe4", "White centralizes the knight."),
        m("c8", "f5", "4... Bf5", "The key Caro-Kann idea: develop the bishop outside the pawn chain."),
        m("e4", "g3", "5. Ng3", "White gains time by attacking the bishop."),
        m("f5", "g6", "5... Bg6", "The bishop keeps its useful diagonal."),
        m("h2", "h4", "6. h4", "White threatens h5 to gain more space against the bishop."),
        m("h7", "h6", "6... h6", "Black gives the bishop a safe retreat square on h7."),
      ],
    },
    variations: [
      {
        name: "Advance Variation",
        moves: [
          m("e2", "e4", "1. e4", "White claims space."), m("c7", "c6", "1... c6", "Black prepares ...d5."),
          m("d2", "d4", "2. d4", "White builds the center."), m("d7", "d5", "2... d5", "Black challenges e4."),
          m("e4", "e5", "3. e5", "White gains space and closes the center."), m("c8", "f5", "3... Bf5", "Black develops the bishop before ...e6."),
          m("g1", "f3", "4. Nf3", "White develops behind the pawn chain."), m("e7", "e6", "4... e6", "Black completes the central structure."),
          m("f1", "e2", "5. Be2", "White prepares to castle."),
        ],
      },
      {
        name: "Exchange Variation",
        moves: [
          m("e2", "e4", "1. e4", "White claims e4."), m("c7", "c6", "1... c6", "Black prepares ...d5."),
          m("d2", "d4", "2. d4", "White builds the center."), m("d7", "d5", "2... d5", "Black challenges it."),
          m("e4", "d5", "3. exd5", "White exchanges in the center."), m("c6", "d5", "3... cxd5", "Black recaptures with a symmetrical structure."),
          m("f1", "d3", "4. Bd3", "White develops actively."), m("b8", "c6", "4... Nc6", "Black develops and pressures d4."),
          m("c2", "c3", "5. c3", "White stabilizes the center."),
        ],
      },
    ],
    quiz: [
      q("Recognition", "Which opening begins 1.e4 c6 2.d4 d5?", ["French Defense", "Caro-Kann Defense", "Scandinavian Defense", "Slav Defense"], 1, "The move ...c6 supports ...d5 and defines the Caro-Kann."),
      q("Strategy", "What is a major benefit of 1...c6 compared with 1...e6?", ["The queen develops faster", "The c8 bishop remains free", "Black wins e4", "White cannot play d4"], 1, "Black can develop the light-squared bishop before closing the structure with ...e6."),
      q("Continuation", "After 3.Nc3 dxe4 4.Nxe4, what is the classical move?", ["...Bf5", "...a6", "...Qxd4", "...f5"], 0, "...Bf5 activates the bishop outside the future ...e6 pawn chain."),
      q("Plan", "Which later pawn break often challenges White’s center?", ["...c5", "...h5", "...b5 only", "...g5"], 0, "Once developed, Black often uses ...c5 to contest d4 and gain activity."),
      q("Mistake", "What should Black usually avoid?", ["Developing the g8 knight", "Playing ...e6 before freeing the c8 bishop", "Castling", "Recapturing on e4"], 1, "Locking the bishop behind ...e6 gives up one of the Caro-Kann’s main advantages."),
    ],
  },
  {
    id: "scotch",
    name: "Scotch Game",
    side: "White",
    difficulty: "Beginner",
    style: ["Tactical", "Open", "Beginner Friendly"],
    startingMoves: "1.e4 e5 2.Nf3 Nc6 3.d4",
    character: "Immediate central clarification",
    skillLevel: "Beginner to intermediate",
    glyph: "♘",
    intro:
      "The Scotch Game challenges Black’s e5 pawn immediately with d4. The early exchanges open lines and give both sides active development, making the opening an excellent laboratory for initiative and piece coordination.",
    objectives: [
      "Open the center before Black settles into a quiet setup",
      "Develop pieces to active squares with clear targets",
      "Use the centralized d4 knight without overexposing it",
      "Exploit open files with rapid castling and rook development",
      "Turn a space advantage into active piece play",
    ],
    plans: {
      white: [
        "Recapture on d4 with the knight for active central placement.",
        "Develop Nc3, Be3, and Qd2 in many lines.",
        "Castle before launching tactics in the open center.",
        "Use e5 when it gains time against a knight.",
      ],
      black: [
        "Attack the d4 knight with ...Nf6 and ...Bc5.",
        "Challenge White’s center using ...d5 when possible.",
        "Develop rapidly; open positions punish lost time.",
        "Avoid grabbing pawns if it leaves the king in the center.",
      ],
    },
    keySquares: [
      { square: "d4", label: "The central confrontation" },
      { square: "e5", label: "White’s space-gaining push" },
      { square: "c6", label: "A frequent knight exchange" },
      { square: "f7", label: "A tactical target in open lines" },
    ],
    pawnStructure:
      "The d- and e-pawns often trade early, leaving open central files. Piece activity, development, and king safety usually matter more than fixed pawn chains.",
    mistakes: [
      "Moving the d4 knight repeatedly without completing development",
      "Winning a pawn while leaving the king in the center",
      "Pushing e5 when it can be attacked and lost",
      "Ignoring Black’s pressure on the central knight",
    ],
    memoryTip: "Open the center, centralize the knight, develop with speed.",
    mainLine: {
      name: "Classical Scotch",
      moves: [
        m("e2", "e4", "1. e4", "White claims central space."),
        m("e7", "e5", "1... e5", "Black matches White in the center."),
        m("g1", "f3", "2. Nf3", "White develops and attacks e5."),
        m("b8", "c6", "2... Nc6", "Black develops and defends e5."),
        m("d2", "d4", "3. d4", "White immediately challenges Black’s central pawn."),
        m("e5", "d4", "3... exd4", "Black accepts the central exchange."),
        m("f3", "d4", "4. Nxd4", "White recaptures and places the knight in the center."),
        m("g8", "f6", "4... Nf6", "Black develops with pressure on e4."),
        m("d4", "c6", "5. Nxc6", "White exchanges the active knight and damages Black’s queenside structure."),
        m("b7", "c6", "5... bxc6", "Black accepts doubled pawns but gains open lines and the bishop pair."),
        m("e4", "e5", "6. e5", "White gains space and attacks the f6 knight."),
        m("d8", "e7", "6... Qe7", "Black pins the e-pawn to the king and counterattacks it."),
      ],
    },
    variations: [
      {
        name: "Schmidt Variation",
        moves: [
          m("e2", "e4", "1. e4", "White claims the center."), m("e7", "e5", "1... e5", "Black mirrors."),
          m("g1", "f3", "2. Nf3", "White develops."), m("b8", "c6", "2... Nc6", "Black develops."),
          m("d2", "d4", "3. d4", "White opens the center."), m("e5", "d4", "3... exd4", "Black exchanges."),
          m("f3", "d4", "4. Nxd4", "The knight occupies d4."), m("g8", "f6", "4... Nf6", "Black pressures e4."),
          m("b1", "c3", "5. Nc3", "White reinforces the center."), m("f8", "b4", "5... Bb4", "Black pins the c3 knight."),
        ],
      },
      {
        name: "Four Knights Scotch",
        moves: [
          m("e2", "e4", "1. e4", "White claims e4."), m("e7", "e5", "1... e5", "Black claims e5."),
          m("g1", "f3", "2. Nf3", "White develops."), m("b8", "c6", "2... Nc6", "Black develops."),
          m("b1", "c3", "3. Nc3", "White develops the second knight."), m("g8", "f6", "3... Nf6", "Black completes the Four Knights setup."),
          m("d2", "d4", "4. d4", "White converts to a Scotch structure."), m("e5", "d4", "4... exd4", "Black opens the center."),
          m("f3", "d4", "5. Nxd4", "White centralizes the knight."),
        ],
      },
    ],
    quiz: [
      q("Recognition", "Which move defines the Scotch after 1.e4 e5 2.Nf3 Nc6?", ["3.Bb5", "3.Bc4", "3.d4", "3.c3"], 2, "3.d4 challenges e5 immediately and defines the Scotch Game."),
      q("Continuation", "After 3.d4 exd4, what is White’s standard recapture?", ["4.Qxd4", "4.Nxd4", "4.c3", "4.Bc4"], 1, "Nxd4 develops the knight to an active central square."),
      q("Character", "What kind of positions does the Scotch usually create?", ["Closed and maneuvering", "Open with active development", "Pawnless endings immediately", "Locked queensides"], 1, "Early central exchanges open lines and reward rapid development."),
      q("Plan", "What should both sides prioritize in the open center?", ["Wing pawn pushes", "King safety and development", "Queen pawn hunting", "Keeping every pawn"], 1, "Open files make undeveloped pieces and an uncastled king especially vulnerable."),
      q("Mistake", "What is a common danger for White’s knight on d4?", ["It cannot move", "Moving it repeatedly can lose development time", "It blocks castling forever", "It is always pinned"], 1, "A centralized knight is useful, but repeated attacks can make White spend too many tempi on it."),
    ],
  },
  {
    id: "queens-gambit",
    name: "Queen’s Gambit",
    side: "White",
    difficulty: "Beginner",
    style: ["Positional", "Strategic", "Beginner Friendly"],
    startingMoves: "1.d4 d5 2.c4",
    character: "Central pressure and positional development",
    skillLevel: "Beginner to advanced",
    glyph: "♕",
    intro:
      "The Queen’s Gambit offers the c-pawn to undermine Black’s d5 pawn. It is not a true pawn sacrifice in most lines: Black has difficulty keeping the extra pawn safely, while White gains central influence and smooth development.",
    objectives: [
      "Pressure the d5 pawn with c4",
      "Build a strong central presence with d4 and e3 or e4",
      "Develop naturally while Black decides the central structure",
      "Use the c-file and queenside majority in later play",
      "Recover the c4 pawn with active piece placement if accepted",
    ],
    plans: {
      white: [
        "Develop Nc3, Nf3, Bg5, and e3 in classical fashion.",
        "Use cxd5 to create a Carlsbad structure when favorable.",
        "Prepare a minority attack with b4-b5 in exchange structures.",
        "Seek e4 when the center allows it.",
      ],
      black: [
        "Support d5 with ...e6 or ...c6.",
        "Challenge White’s center with ...c5.",
        "If accepting c4, return the pawn to finish development.",
        "Develop the c8 bishop before it becomes restricted when possible.",
      ],
    },
    keySquares: [
      { square: "d5", label: "The pawn under pressure" },
      { square: "c4", label: "The gambit lever" },
      { square: "e4", label: "White’s ideal central expansion" },
      { square: "c5", label: "Black’s freeing break" },
    ],
    pawnStructure:
      "The Queen’s Gambit often produces an isolated queen’s pawn, hanging pawns, or the Carlsbad structure. Each has a clear plan, making the opening ideal for learning positional chess.",
    mistakes: [
      "Trying to hold the c4 pawn at the cost of development",
      "Blocking the c8 bishop without a plan",
      "Releasing central tension automatically",
      "Playing a minority attack before completing development",
    ],
    memoryTip: "Use c4 to question d5, then develop behind the pressure.",
    mainLine: {
      name: "Queen’s Gambit Declined",
      moves: [
        m("d2", "d4", "1. d4", "White claims central space and opens the c1 bishop."),
        m("d7", "d5", "1... d5", "Black establishes an equal central foothold."),
        m("c2", "c4", "2. c4", "White challenges the d5 pawn with the Queen’s Gambit."),
        m("e7", "e6", "2... e6", "Black supports d5 and declines the pawn offer."),
        m("b1", "c3", "3. Nc3", "White adds pressure to d5 and develops."),
        m("g8", "f6", "3... Nf6", "Black develops and reinforces d5."),
        m("c1", "g5", "4. Bg5", "White pins the f6 knight, increasing pressure on the center."),
        m("f8", "e7", "4... Be7", "Black breaks the pin and prepares to castle."),
        m("e2", "e3", "5. e3", "White supports d4 and opens the f1 bishop."),
        m("e8", "g8", "5... O-O", "Black secures the king."),
        m("g1", "f3", "6. Nf3", "White completes natural kingside development."),
        m("h7", "h6", "6... h6", "Black asks the g5 bishop to decide its future."),
      ],
    },
    variations: [
      {
        name: "Queen’s Gambit Accepted",
        moves: [
          m("d2", "d4", "1. d4", "White takes the center."), m("d7", "d5", "1... d5", "Black matches it."),
          m("c2", "c4", "2. c4", "White offers the c-pawn."), m("d5", "c4", "2... dxc4", "Black accepts the gambit."),
          m("g1", "f3", "3. Nf3", "White develops instead of rushing to recover the pawn."), m("g8", "f6", "3... Nf6", "Black develops."),
          m("e2", "e3", "4. e3", "White opens the bishop and prepares Bxc4."), m("e7", "e6", "4... e6", "Black supports development."),
          m("f1", "c4", "5. Bxc4", "White regains the pawn with an active bishop."), m("c7", "c5", "5... c5", "Black challenges the center."),
        ],
      },
      {
        name: "Exchange Structure",
        moves: [
          m("d2", "d4", "1. d4", "White claims the center."), m("d7", "d5", "1... d5", "Black meets it."),
          m("c2", "c4", "2. c4", "White challenges d5."), m("e7", "e6", "2... e6", "Black supports d5."),
          m("b1", "c3", "3. Nc3", "White develops."), m("g8", "f6", "3... Nf6", "Black develops."),
          m("c4", "d5", "4. cxd5", "White defines the Carlsbad structure."), m("e6", "d5", "4... exd5", "Black recaptures with the e-pawn."),
        ],
      },
    ],
    quiz: [
      q("Recognition", "Which moves begin the Queen’s Gambit?", ["1.d4 d5 2.c4", "1.e4 e5 2.f4", "1.c4 e5", "1.d4 Nf6 2.c4 g6"], 0, "White’s 2.c4 challenges Black’s d5 pawn."),
      q("Understanding", "Why is the Queen’s Gambit usually not a true pawn sacrifice?", ["The pawn cannot be captured", "White can normally recover c4", "Black is in check", "The queen protects c4"], 1, "Holding the extra c4 pawn is difficult without making concessions, so White usually regains it."),
      q("Plan", "What does 2.c4 primarily attack?", ["e5", "d5", "b7", "f7"], 1, "The c-pawn acts as a lever against Black’s central d5 pawn."),
      q("Accepted", "In the accepted line, how does White often recover the pawn?", ["Qa4+", "Bxc4 after e3", "Nxb5", "f3"], 1, "Nf3 and e3 allow the f1 bishop to recapture on c4 with development."),
      q("Mistake", "What is risky for Black after accepting the gambit?", ["Returning the pawn", "Trying to hold c4 with many pawn moves", "Developing Nf6", "Playing e6"], 1, "Defending the extra pawn can cost too many tempi and leave Black seriously behind in development."),
    ],
  },
  {
    id: "slav",
    name: "Slav Defense",
    side: "Black",
    difficulty: "Intermediate",
    style: ["Solid", "Positional", "Strategic"],
    startingMoves: "1.d4 d5 2.c4 c6",
    character: "Solid d5 support with flexible development",
    skillLevel: "Intermediate",
    glyph: "♝",
    intro:
      "The Slav Defense supports d5 with the c-pawn, allowing Black’s light-squared bishop to develop freely. It combines structural reliability with more active possibilities than many closed defenses.",
    objectives: [
      "Defend d5 without blocking the c8 bishop",
      "Develop naturally with ...Nf6 and ...Bf5",
      "Choose the right moment to capture on c4",
      "Challenge White’s center with ...c5 or ...e5",
      "Maintain a sound pawn structure into the endgame",
    ],
    plans: {
      white: [
        "Develop Nc3 and Nf3 while keeping pressure on d5.",
        "Use e3 or Qc2 to recover c4 after ...dxc4.",
        "Gain queenside space with a4 when Black tries ...b5.",
        "Seek e4 if Black gives enough time.",
      ],
      black: [
        "Develop the c8 bishop outside the pawn chain.",
        "Use ...dxc4 when it gains time or enables ...b5.",
        "Play ...e6 after the bishop is active.",
        "Look for the freeing ...c5 break in settled structures.",
      ],
    },
    keySquares: [
      { square: "d5", label: "The firmly supported center" },
      { square: "f5", label: "The bishop’s active post" },
      { square: "c4", label: "The central tension point" },
      { square: "e4", label: "White’s expansion square" },
    ],
    pawnStructure:
      "Black’s c6–d5 chain is compact and leaves the c8 bishop free. If Black captures on c4, queenside pawns may expand with ...b5 while White works to recover the pawn.",
    mistakes: [
      "Playing ...e6 before developing the c8 bishop without a reason",
      "Trying to keep the c4 pawn while allowing a4 to undermine ...b5",
      "Remaining cramped instead of using a timely ...c5 break",
      "Developing the b8 knight where it blocks the c-pawn’s role",
    ],
    memoryTip: "Support d5 with c6, then let the bishop breathe.",
    mainLine: {
      name: "Main Line Slav",
      moves: [
        m("d2", "d4", "1. d4", "White claims central space."),
        m("d7", "d5", "1... d5", "Black establishes a central pawn."),
        m("c2", "c4", "2. c4", "White challenges d5."),
        m("c7", "c6", "2... c6", "Black supports d5 while keeping the c8 bishop free."),
        m("g1", "f3", "3. Nf3", "White develops and controls e5."),
        m("g8", "f6", "3... Nf6", "Black develops naturally and reinforces d5."),
        m("b1", "c3", "4. Nc3", "White increases central pressure."),
        m("d5", "c4", "4... dxc4", "Black releases the tension and temporarily wins the c-pawn."),
        m("a2", "a4", "5. a4", "White prevents ...b5 from safely holding the extra pawn."),
        m("c8", "f5", "5... Bf5", "Black develops the bishop actively before playing ...e6."),
        m("e2", "e3", "6. e3", "White opens the f1 bishop to recover c4."),
        m("e7", "e6", "6... e6", "Black now completes a solid central structure."),
      ],
    },
    variations: [
      {
        name: "Exchange Slav",
        moves: [
          m("d2", "d4", "1. d4", "White claims d4."), m("d7", "d5", "1... d5", "Black claims d5."),
          m("c2", "c4", "2. c4", "White pressures the center."), m("c7", "c6", "2... c6", "Black supports d5."),
          m("c4", "d5", "3. cxd5", "White creates a symmetrical exchange structure."), m("c6", "d5", "3... cxd5", "Black restores the central pawn."),
          m("b1", "c3", "4. Nc3", "White develops."), m("g8", "f6", "4... Nf6", "Black develops."),
        ],
      },
      {
        name: "Triangle Setup",
        moves: [
          m("d2", "d4", "1. d4", "White claims the center."), m("d7", "d5", "1... d5", "Black mirrors."),
          m("c2", "c4", "2. c4", "White challenges d5."), m("e7", "e6", "2... e6", "Black reinforces d5."),
          m("b1", "c3", "3. Nc3", "White develops."), m("c7", "c6", "3... c6", "Black forms the triangle pawn structure."),
          m("e2", "e4", "4. e4", "White grabs the center, entering sharp theory."),
        ],
      },
    ],
    quiz: [
      q("Recognition", "Which moves define the Slav Defense?", ["1.d4 d5 2.c4 c6", "1.d4 d5 2.c4 e6", "1.e4 c6", "1.d4 Nf6"], 0, "...c6 supports d5 and keeps the c8 bishop’s diagonal open."),
      q("Strategy", "What is the Slav’s key advantage over an early ...e6 setup?", ["It attacks the queen", "The c8 bishop stays free", "It wins c4", "It stops Nf3"], 1, "The light-squared bishop can develop to f5 or g4 before ...e6."),
      q("Continuation", "After ...dxc4, why is a4 useful for White?", ["It attacks e8", "It discourages ...b5 from holding c4", "It prepares Ra3 mate", "It traps the f6 knight"], 1, "a4 undermines Black’s typical ...b5 pawn support."),
      q("Plan", "Which square is a natural home for Black’s light bishop?", ["f5", "h3", "a6 only", "e8"], 0, "...Bf5 develops the bishop actively before Black closes with ...e6."),
      q("Mistake", "What can leave Black cramped?", ["Developing Nf6", "Never seeking ...c5", "Supporting d5", "Castling"], 1, "The ...c5 break is often essential to challenge White’s center and gain space."),
    ],
  },
  {
    id: "kings-indian",
    name: "King’s Indian Defense",
    side: "Black",
    difficulty: "Intermediate",
    style: ["Aggressive", "Dynamic", "Hypermodern"],
    startingMoves: "1.d4 Nf6 2.c4 g6 3.Nc3 Bg7",
    character: "Closed center and opposite-wing attacks",
    skillLevel: "Intermediate to advanced",
    glyph: "♚",
    intro:
      "The King’s Indian lets White build a broad pawn center, then attacks it with pieces and pawn breaks. Black usually castles early and seeks dynamic kingside play, even when White holds more queenside space.",
    objectives: [
      "Allow and then challenge White’s pawn center",
      "Fianchetto the dark-squared bishop on g7",
      "Castle quickly before striking with ...e5 or ...c5",
      "Create kingside play with ...f5 in closed centers",
      "Accept space disadvantage in exchange for dynamic chances",
    ],
    plans: {
      white: [
        "Use d5 to close the center and gain queenside space.",
        "Expand with b4 and c5 in classical structures.",
        "Keep the king safe from Black’s ...f5 attack.",
        "Use the Sämisch setup for extra central support.",
      ],
      black: [
        "Strike with ...e5 and close with ...d4-d5 when appropriate.",
        "Prepare ...f5 with ...Nbd7 and ...Nh5 or ...Ne8.",
        "Use the g7 bishop against the long diagonal.",
        "Attack on the kingside while White expands on the queenside.",
      ],
    },
    keySquares: [
      { square: "e5", label: "Black’s main central break" },
      { square: "f5", label: "The kingside attacking lever" },
      { square: "d5", label: "White’s space-gaining advance" },
      { square: "g7", label: "The fianchetto bishop’s post" },
    ],
    pawnStructure:
      "After ...e5 and d5, the center locks. White’s chain points queenside and Black’s chain points kingside, creating the opening’s famous opposite-wing races.",
    mistakes: [
      "Launching ...f5 before the center and king are ready",
      "Trading the g7 bishop without a concrete benefit",
      "Playing passively in a position that requires counterplay",
      "Ignoring White’s queenside breakthrough while attacking",
    ],
    memoryTip: "Let the center grow, lock it, then attack its king-side edge.",
    mainLine: {
      name: "Classical King’s Indian",
      moves: [
        m("d2", "d4", "1. d4", "White claims central space."),
        m("g8", "f6", "1... Nf6", "Black controls e4 without committing a central pawn."),
        m("c2", "c4", "2. c4", "White builds a broad queen-pawn center."),
        m("g7", "g6", "2... g6", "Black prepares to fianchetto the dark-squared bishop."),
        m("b1", "c3", "3. Nc3", "White reinforces d5 and prepares e4."),
        m("f8", "g7", "3... Bg7", "The bishop takes aim along the long diagonal."),
        m("e2", "e4", "4. e4", "White establishes the ideal pawn center."),
        m("d7", "d6", "4... d6", "Black restrains e5 and prepares a central break."),
        m("g1", "f3", "5. Nf3", "White develops and supports the center."),
        m("e8", "g8", "5... O-O", "Black castles before challenging the center."),
        m("f1", "e2", "6. Be2", "White prepares to castle and completes development."),
        m("e7", "e5", "6... e5", "Black strikes at the center and defines the classical structure."),
      ],
    },
    variations: [
      {
        name: "Classical Variation",
        moves: [
          m("d2", "d4", "1. d4", "White takes the center."), m("g8", "f6", "1... Nf6", "Black develops flexibly."),
          m("c2", "c4", "2. c4", "White expands."), m("g7", "g6", "2... g6", "Black prepares the fianchetto."),
          m("b1", "c3", "3. Nc3", "White develops."), m("f8", "g7", "3... Bg7", "Black completes the fianchetto."),
          m("e2", "e4", "4. e4", "White builds the center."), m("d7", "d6", "4... d6", "Black prepares ...e5."),
        ],
      },
      {
        name: "Sämisch Variation",
        moves: [
          m("d2", "d4", "1. d4", "White claims d4."), m("g8", "f6", "1... Nf6", "Black develops."),
          m("c2", "c4", "2. c4", "White expands."), m("g7", "g6", "2... g6", "Black prepares ...Bg7."),
          m("b1", "c3", "3. Nc3", "White develops."), m("f8", "g7", "3... Bg7", "Black fianchettos."),
          m("e2", "e4", "4. e4", "White builds the center."), m("d7", "d6", "4... d6", "Black prepares a break."),
          m("f2", "f3", "5. f3", "White strongly supports e4 and prepares aggressive expansion."), m("e8", "g8", "5... O-O", "Black castles safely."),
        ],
      },
      {
        name: "Fianchetto Variation",
        moves: [
          m("d2", "d4", "1. d4", "White claims the center."), m("g8", "f6", "1... Nf6", "Black develops."),
          m("c2", "c4", "2. c4", "White expands."), m("g7", "g6", "2... g6", "Black prepares the bishop."),
          m("g1", "f3", "3. Nf3", "White develops flexibly."), m("f8", "g7", "3... Bg7", "Black fianchettos."),
          m("g2", "g3", "4. g3", "White prepares a matching fianchetto."), m("e8", "g8", "4... O-O", "Black castles."),
          m("f1", "g2", "5. Bg2", "White completes a solid positional setup."),
        ],
      },
    ],
    quiz: [
      q("Recognition", "Which setup signals the King’s Indian Defense?", ["...d5 and ...c6", "...Nf6, ...g6, and ...Bg7", "...e6 and ...Bb4", "...c5 only"], 1, "The kingside fianchetto with ...Nf6, ...g6, and ...Bg7 is the core setup."),
      q("Concept", "What does ‘hypermodern’ mean here?", ["Avoiding development", "Controlling the center with pieces before attacking it", "Moving the king early", "Trading every central pawn"], 1, "Black permits White’s pawn center, then attacks it with pieces and pawn breaks."),
      q("Plan", "What is Black’s main kingside pawn break in closed lines?", ["...a5", "...b5", "...f5", "...h5 only"], 2, "...f5 starts Black’s thematic kingside counterplay."),
      q("Structure", "After ...e5 and d5, where do the sides usually play?", ["Both on the queenside", "White queenside, Black kingside", "Both in the center only", "White kingside, Black queenside"], 1, "The closed pawn chains point the armies toward opposite wings."),
      q("Mistake", "Which piece should Black avoid trading casually?", ["The g7 bishop", "The a8 rook", "The b8 knight", "The queen’s bishop always"], 0, "The g7 bishop is a key attacker and central pressure piece in the King’s Indian."),
    ],
  },
  {
    id: "english",
    name: "English Opening",
    side: "White",
    difficulty: "Intermediate",
    style: ["Positional", "Flexible", "Strategic"],
    startingMoves: "1.c4",
    character: "Flexible flank control and transpositions",
    skillLevel: "Intermediate",
    glyph: "♙",
    intro:
      "The English Opening controls d5 from the flank and delays the central pawn commitment. Its flexibility allows White to steer into unique reversed-Sicilian structures or transpose into familiar queen-pawn openings.",
    objectives: [
      "Control d5 with the c-pawn",
      "Keep the central pawn structure flexible",
      "Fianchetto the light-squared bishop in many systems",
      "Use queenside space without neglecting the center",
      "Choose favorable transpositions based on Black’s setup",
    ],
    plans: {
      white: [
        "Develop Nc3, Nf3, g3, and Bg2 in a flexible order.",
        "Use b4 to gain queenside space in suitable positions.",
        "Prepare d4 or e4 once Black’s setup is known.",
        "In reversed Sicilians, exploit the extra tempo patiently.",
      ],
      black: [
        "Occupy the center with ...e5 or mirror using ...c5.",
        "Challenge the g2 bishop’s diagonal.",
        "Use ...d5 when it can be established safely.",
        "Avoid drifting into a passive copycat setup.",
      ],
    },
    keySquares: [
      { square: "d5", label: "The c-pawn’s target square" },
      { square: "c4", label: "White’s flexible first foothold" },
      { square: "g2", label: "The fianchetto bishop’s post" },
      { square: "e4", label: "A later Botvinnik-style center" },
    ],
    pawnStructure:
      "English structures vary widely. Common themes include a c4–g2 queenside grip, symmetrical c-pawns, or a Botvinnik formation with pawns on c4, e4, and d3.",
    mistakes: [
      "Playing only on the flank while Black takes the whole center",
      "Transposing into an unfamiliar opening accidentally",
      "Fianchettoing without protecting the long diagonal",
      "Expanding with b4 before the center and king are ready",
    ],
    memoryTip: "Control d5 from the side and keep the center flexible.",
    mainLine: {
      name: "Reversed Sicilian",
      moves: [
        m("c2", "c4", "1. c4", "White controls d5 from the flank and preserves central flexibility."),
        m("e7", "e5", "1... e5", "Black occupies the center, creating a reversed Sicilian structure."),
        m("b1", "c3", "2. Nc3", "White reinforces d5 and develops naturally."),
        m("g8", "f6", "2... Nf6", "Black develops and controls e4 and d5."),
        m("g1", "f3", "3. Nf3", "White increases pressure on e5 and prepares rapid castling."),
        m("b8", "c6", "3... Nc6", "Black supports e5 and develops."),
        m("g2", "g3", "4. g3", "White prepares the signature kingside fianchetto."),
        m("d7", "d5", "4... d5", "Black uses the center before White can fully restrain it."),
        m("c4", "d5", "5. cxd5", "White exchanges to prevent Black from maintaining the full pawn duo."),
        m("f6", "d5", "5... Nxd5", "Black recaptures with active central development."),
        m("f1", "g2", "6. Bg2", "White completes the fianchetto and attacks d5."),
        m("d5", "b6", "6... Nb6", "Black preserves the knight and keeps the position flexible."),
      ],
    },
    variations: [
      {
        name: "Symmetrical English",
        moves: [
          m("c2", "c4", "1. c4", "White controls d5."), m("c7", "c5", "1... c5", "Black mirrors the flank control."),
          m("b1", "c3", "2. Nc3", "White develops."), m("b8", "c6", "2... Nc6", "Black mirrors."),
          m("g2", "g3", "3. g3", "White prepares the fianchetto."), m("g7", "g6", "3... g6", "Black does the same."),
          m("f1", "g2", "4. Bg2", "White controls the long diagonal."), m("f8", "g7", "4... Bg7", "Black develops symmetrically."),
        ],
      },
      {
        name: "Botvinnik Setup",
        moves: [
          m("c2", "c4", "1. c4", "White begins on the flank."), m("e7", "e5", "1... e5", "Black takes central space."),
          m("b1", "c3", "2. Nc3", "White develops."), m("b8", "c6", "2... Nc6", "Black develops."),
          m("g2", "g3", "3. g3", "White prepares Bg2."), m("g7", "g6", "3... g6", "Black prepares Bg7."),
          m("f1", "g2", "4. Bg2", "White fianchettos."), m("f8", "g7", "4... Bg7", "Black mirrors."),
          m("e2", "e4", "5. e4", "White builds a Botvinnik pawn triangle."), m("d7", "d6", "5... d6", "Black stabilizes the center."),
          m("d2", "d3", "6. d3", "White completes the flexible central shell."),
        ],
      },
    ],
    quiz: [
      q("Recognition", "Which first move defines the English Opening?", ["1.e4", "1.d4", "1.c4", "1.Nf3 only"], 2, "1.c4 controls d5 from the flank and defines the English."),
      q("Concept", "What is the English Opening’s main early advantage?", ["It forces mate", "It keeps central commitments flexible", "It wins d5", "It prevents ...e5"], 1, "White can choose d4, e4, or neither after seeing Black’s setup."),
      q("Strategy", "Which square does the c4 pawn control?", ["b5", "d5", "e4", "c5"], 1, "From c4, White’s pawn directly controls d5."),
      q("Setup", "Where is White’s light-squared bishop commonly developed?", ["g2", "a2", "h3", "c6"], 0, "A g3–Bg2 fianchetto is one of the English Opening’s most characteristic setups."),
      q("Mistake", "What is a danger of overly passive flank play?", ["Black may occupy the whole center", "White loses castling rights", "The c-pawn promotes", "Black must trade queens"], 0, "Flexibility still requires central control; otherwise Black can build an imposing pawn center."),
    ],
  },
];
