import { defineLineFromSegments as line, definePly as ply } from "./schema.js";

const ITALIAN = [
  ply("e2", "e4", "e4", "White occupies the center and opens the queen and bishop."),
  ply("e7", "e5", "e5", "Black claims equal central space and frees the kingside pieces."),
  ply("g1", "f3", "Nf3", "The knight develops with tempo against e5."),
  ply("b8", "c6", "Nc6", "Black protects e5 while developing toward the center."),
  ply("f1", "c4", "Bc4", "White activates the bishop toward f7, Black's least-defended starting pawn."),
];

const RUY = [
  ply("e2", "e4", "e4", "White takes central space and frees the kingside."),
  ply("e7", "e5", "e5", "Black establishes an equal center."),
  ply("g1", "f3", "Nf3", "White develops with an attack on e5."),
  ply("b8", "c6", "Nc6", "Black defends e5 and develops."),
  ply("f1", "b5", "Bb5", "The bishop pins the main defender of e5 and creates long-term queenside pressure."),
];

const SICILIAN_OPEN = [
  ply("e2", "e4", "e4", "White claims the center and opens rapid development."),
  ply("c7", "c5", "c5", "Black attacks d4 from the flank and creates an asymmetric pawn structure."),
  ply("g1", "f3", "Nf3", "White prepares d4 and controls e5."),
  ply("d7", "d6", "d6", "Black restrains e5 and prepares kingside development."),
  ply("d2", "d4", "d4", "White opens the center before Black can consolidate."),
  ply("c5", "d4", "cxd4", "Black exchanges the c-pawn for White's central d-pawn and opens the c-file."),
  ply("f3", "d4", "Nxd4", "White recaptures with development and occupies a central square."),
  ply("g8", "f6", "Nf6", "Black develops with tempo against e4."),
  ply("b1", "c3", "Nc3", "White protects e4 and completes the Open Sicilian setup."),
];

const FRENCH = [
  ply("e2", "e4", "e4", "White takes central space and opens two pieces."),
  ply("e7", "e6", "e6", "Black prepares ...d5 while opening the dark-squared bishop."),
  ply("d2", "d4", "d4", "White builds the full classical pawn center."),
  ply("d7", "d5", "d5", "Black attacks e4 and fixes the characteristic central tension."),
];

const CARO = [
  ply("e2", "e4", "e4", "White claims central space."),
  ply("c7", "c6", "c6", "Black prepares ...d5 while keeping the c8 bishop's diagonal open."),
  ply("d2", "d4", "d4", "White establishes the ideal central duo."),
  ply("d7", "d5", "d5", "Black challenges e4 with a solidly supported pawn."),
];

const SCOTCH = [
  ply("e2", "e4", "e4", "White claims the center and opens the kingside."),
  ply("e7", "e5", "e5", "Black matches the central claim."),
  ply("g1", "f3", "Nf3", "White develops with pressure on e5."),
  ply("b8", "c6", "Nc6", "Black defends e5 and develops."),
  ply("d2", "d4", "d4", "White immediately challenges the center to gain open piece play."),
  ply("e5", "d4", "exd4", "Black accepts the exchange and opens the e-file."),
];

const QUEENS_GAMBIT = [
  ply("d2", "d4", "d4", "White takes central space and frees the c1 bishop."),
  ply("d7", "d5", "d5", "Black creates an equal central foothold."),
  ply("c2", "c4", "c4", "White attacks d5 from the flank and offers a temporary pawn."),
];

const SLAV = [
  ply("d2", "d4", "d4", "White claims central space."),
  ply("d7", "d5", "d5", "Black matches White in the center."),
  ply("c2", "c4", "c4", "White increases pressure on d5."),
  ply("c7", "c6", "c6", "Black supports d5 without blocking the c8 bishop."),
];

const KID = [
  ply("d2", "d4", "d4", "White takes central space."),
  ply("g8", "f6", "Nf6", "Black controls e4 without fixing a central pawn."),
  ply("c2", "c4", "c4", "White expands the queen's-pawn center."),
  ply("g7", "g6", "g6", "Black prepares the kingside fianchetto."),
  ply("b1", "c3", "Nc3", "White supports e4 and d5."),
  ply("f8", "g7", "Bg7", "Black activates the bishop against the center."),
];

const ENGLISH = [
  ply("c2", "c4", "c4", "White controls d5 from the flank and keeps the center flexible."),
];

export const OPENING_VARIATIONS = {
  italian: [
    line(
      "Hungarian Defense",
      ITALIAN,
      [
        ply("f8", "e7", "Be7", "Black chooses a compact bishop square that avoids early tactics on f7."),
        ply("d2", "d4", "d4", "White uses the quiet bishop placement to occupy more central space."),
        ply("d7", "d6", "d6", "Black reinforces e5 and creates a route for the c8 bishop."),
        ply("d4", "d5", "d5", "White gains space and restricts the c6 knight."),
        ply("c6", "b8", "Nb8", "The knight retreats so it can reroute through d7 without blocking the c-pawn."),
        ply("c4", "d3", "Bd3", "White redirects the bishop toward the kingside and prepares castling."),
        ply("g8", "f6", "Nf6", "Black develops against e4 and completes the kingside setup."),
      ],
    ),
    line(
      "Scotch Gambit",
      SCOTCH,
      [
        ply("f1", "c4", "Bc4", "White delays recapturing to gain rapid development and pressure on f7."),
        ply("f8", "c5", "Bc5", "Black develops actively and protects f2-related tactical ideas."),
        ply("c2", "c3", "c3", "White offers another pawn to build a center with tempo."),
        ply("g8", "f6", "Nf6", "Black develops and attacks e4 before accepting more material."),
        ply("c3", "d4", "cxd4", "White restores the pawn balance and creates a broad central duo."),
        ply("c5", "b4", "Bb4+", "Black checks with development and interferes with easy castling."),
      ],
    ),
    line(
      "Max Lange Attack",
      ITALIAN.slice(0, 4),
      [
        ply("f1", "c4", "Bc4", "White places the bishop on the attacking f7 diagonal."),
        ply("g8", "f6", "Nf6", "Black develops and attacks e4."),
        ply("d2", "d4", "d4", "White opens the center while development is ahead."),
        ply("e5", "d4", "exd4", "Black releases the tension and accepts the central pawn."),
        ply("e1", "g1", "O-O", "White castles instead of recapturing, prioritizing activity."),
        ply("f8", "c5", "Bc5", "Black develops and reinforces the d4 pawn tactically."),
        ply("e4", "e5", "e5", "White drives the f6 knight and opens the e-file for attacking play."),
        ply("d7", "d5", "d5", "Black counters in the center, the essential response to the pawn advance."),
      ],
    ),
  ],
  "ruy-lopez": [
    line(
      "Open Ruy López",
      RUY,
      [
        ply("a7", "a6", "a6", "Black asks the bishop to decide before resolving the e5 pressure."),
        ply("b5", "a4", "Ba4", "White keeps the pin and preserves the bishop pair."),
        ply("g8", "f6", "Nf6", "Black develops with an attack on e4."),
        ply("e1", "g1", "O-O", "White secures the king and makes the e-pawn tactically expendable."),
        ply("f6", "e4", "Nxe4", "Black captures e4 because the center will be supported by active piece play."),
        ply("d2", "d4", "d4", "White opens lines and attacks the centralized knight."),
        ply("b7", "b5", "b5", "Black gains a tempo on the bishop and holds the extra central pawn."),
        ply("a4", "b3", "Bb3", "White preserves the bishop's pressure along the a2–g8 diagonal."),
        ply("d7", "d5", "d5", "Black supports e4 and establishes an active open center."),
      ],
    ),
    line(
      "Schliemann Defense",
      RUY,
      [
        ply("f7", "f5", "f5", "Black counterattacks e4 immediately, accepting king weakness for activity."),
        ply("b1", "c3", "Nc3", "White develops and adds support to e4 before taking on f5."),
        ply("f5", "e4", "fxe4", "Black removes White's central pawn and opens the f-file."),
        ply("c3", "e4", "Nxe4", "White recaptures with development and centralizes the queen's knight."),
        ply("d7", "d5", "d5", "Black hits both the bishop and central knights through tactical pressure."),
        ply("f3", "e5", "Nxe5", "The kingside knight removes Black's remaining central pawn."),
        ply("d5", "e4", "dxe4", "Black captures the other knight and resolves the overloaded center."),
        ply("e5", "c6", "Nxc6", "White removes the c6 knight and threatens material recovery."),
        ply("d8", "g5", "Qg5", "Black attacks b5 and g2 while using the open queen diagonal."),
      ],
    ),
    line(
      "Chigorin Variation",
      RUY,
      [
        ply("a7", "a6", "a6", "Black gains space and asks the bishop to choose."),
        ply("b5", "a4", "Ba4", "White keeps the bishop on the pinning diagonal."),
        ply("g8", "f6", "Nf6", "Black attacks e4 and develops."),
        ply("e1", "g1", "O-O", "White secures the king."),
        ply("f8", "e7", "Be7", "Black prepares castling and keeps the bishop flexible."),
        ply("f1", "e1", "Re1", "White reinforces e4 and places the rook on the openable file."),
        ply("b7", "b5", "b5", "Black gains queenside space and sends the bishop to its main retreat."),
        ply("a4", "b3", "Bb3", "White maintains pressure on f7 and the center."),
        ply("d7", "d6", "d6", "Black supports e5 and opens the c8 bishop."),
        ply("c2", "c3", "c3", "White prepares d4 and gives the bishop an escape square."),
        ply("e8", "g8", "O-O", "Black completes king safety before central play."),
        ply("h2", "h3", "h3", "White prevents ...Bg4 and gives the king luft."),
        ply("c6", "a5", "Na5", "The Chigorin knight attacks b3 and clears the c-pawn for ...c5."),
      ],
    ),
    line(
      "Breyer Variation",
      RUY,
      [
        ply("a7", "a6", "a6", "Black asks the bishop to retreat before choosing a setup."),
        ply("b5", "a4", "Ba4", "White preserves the Ruy bishop."),
        ply("g8", "f6", "Nf6", "Black develops against e4."),
        ply("e1", "g1", "O-O", "White secures the king."),
        ply("f8", "e7", "Be7", "Black prepares castling."),
        ply("f1", "e1", "Re1", "White adds support to e4."),
        ply("b7", "b5", "b5", "Black gains queenside space."),
        ply("a4", "b3", "Bb3", "White keeps the bishop on the long diagonal."),
        ply("d7", "d6", "d6", "Black stabilizes e5."),
        ply("c2", "c3", "c3", "White prepares the central d4 break."),
        ply("e8", "g8", "O-O", "Black makes the king safe."),
        ply("h2", "h3", "h3", "White prevents a pin on g4."),
        ply("c6", "b8", "Nb8", "The knight retreats so it can reroute to d7 and free the c-pawn."),
        ply("d2", "d4", "d4", "White finally claims the full center."),
        ply("b8", "d7", "Nbd7", "Black completes the Breyer reroute toward f8 and c5."),
      ],
    ),
  ],
  sicilian: [
    line(
      "Najdorf Variation",
      SICILIAN_OPEN,
      [
        ply("a7", "a6", "a6", "Black prevents Nb5, prepares ...b5, and keeps the central pawn choice flexible."),
        ply("c1", "e3", "Be3", "White develops and supports Qd2 with possible queenside castling."),
        ply("e7", "e6", "e6", "Black restrains e5 and opens the f8 bishop."),
        ply("f2", "f3", "f3", "White reinforces e4 and prepares g4 without allowing ...Ng4."),
        ply("b7", "b5", "b5", "Black begins queenside expansion and gives the c8 bishop more scope."),
      ],
    ),
    line(
      "Dragon Variation",
      SICILIAN_OPEN,
      [
        ply("g7", "g6", "g6", "Black prepares the Dragon bishop on the long diagonal toward d4."),
        ply("c1", "e3", "Be3", "White develops and prepares Qd2 and long castling."),
        ply("f8", "g7", "Bg7", "Black activates the bishop against the centralized d4 knight."),
        ply("f2", "f3", "f3", "White strengthens e4 and prepares a kingside pawn storm."),
        ply("e8", "g8", "O-O", "Black castles into the coming attack to activate the rook and finish development."),
        ply("d1", "d2", "Qd2", "White connects the queen and bishop, preparing Bh6 and O-O-O."),
      ],
    ),
    line(
      "Classical Variation",
      SICILIAN_OPEN,
      [
        ply("b8", "c6", "Nc6", "Black develops another piece against d4 and e5."),
        ply("c1", "g5", "Bg5", "White pins the f6 knight and increases control over d5."),
        ply("e7", "e6", "e6", "Black challenges the bishop's influence and opens the f8 bishop."),
        ply("d1", "d2", "Qd2", "White prepares long castling and supports the g5 bishop."),
        ply("f8", "e7", "Be7", "Black breaks the pin and readies kingside castling."),
      ],
    ),
    line(
      "Scheveningen Variation",
      SICILIAN_OPEN,
      [
        ply("e7", "e6", "e6", "Black builds the compact d6–e6 center and controls d5."),
        ply("g2", "g4", "g4", "White launches the Keres Attack before castling to drive the f6 knight."),
        ply("h7", "h6", "h6", "Black slows g5 and asks White to commit more pawns."),
        ply("c1", "e3", "Be3", "White develops and supports queenside castling."),
        ply("b7", "b5", "b5", "Black creates queenside counterplay against White's likely king position."),
      ],
    ),
    line(
      "Sveshnikov Variation",
      [
        ply("e2", "e4", "e4", "White occupies the center."),
        ply("c7", "c5", "c5", "Black creates an asymmetric fight for d4."),
        ply("g1", "f3", "Nf3", "White prepares d4."),
        ply("b8", "c6", "Nc6", "Black pressures d4 and keeps ...e5 available."),
        ply("d2", "d4", "d4", "White opens the center."),
        ply("c5", "d4", "cxd4", "Black exchanges the flank pawn for the central pawn."),
        ply("f3", "d4", "Nxd4", "White recaptures with development."),
        ply("g8", "f6", "Nf6", "Black develops with pressure on e4."),
        ply("b1", "c3", "Nc3", "White reinforces e4."),
        ply("e7", "e5", "e5", "Black drives the d4 knight and accepts a weak d5 square for active play."),
        ply("d4", "b5", "Ndb5", "The knight heads toward d6 and avoids blocking the c3 knight."),
        ply("d7", "d6", "d6", "Black controls e5 and prepares a6 against the b5 knight."),
        ply("c1", "g5", "Bg5", "White pins the f6 knight and increases pressure on d5."),
        ply("a7", "a6", "a6", "Black asks the b5 knight to choose its main route."),
      ],
    ),
    line(
      "Grand Prix Attack",
      [
        ply("e2", "e4", "e4", "White takes central space."),
        ply("c7", "c5", "c5", "Black challenges d4 asymmetrically."),
        ply("b1", "c3", "Nc3", "White develops while keeping the d-pawn back for a kingside setup."),
        ply("b8", "c6", "Nc6", "Black develops and controls d4."),
        ply("f2", "f4", "f4", "White builds kingside space and prepares a direct attack."),
        ply("g7", "g6", "g6", "Black fianchettos to control the dark squares weakened by f4."),
        ply("g1", "f3", "Nf3", "White develops and supports e5."),
        ply("f8", "g7", "Bg7", "Black activates the long diagonal against c3 and b2."),
        ply("f1", "b5", "Bb5", "White develops with a pin and prepares castling."),
        ply("c6", "d4", "Nd4", "Black occupies the central outpost created by White's missing d-pawn advance."),
      ],
    ),
  ],
  french: [
    line(
      "Winawer Variation",
      FRENCH,
      [
        ply("b1", "c3", "Nc3", "White protects e4 and increases central control."),
        ply("f8", "b4", "Bb4", "Black pins the defender of e4 and creates structural pressure."),
        ply("e4", "e5", "e5", "White closes the center and gains kingside space."),
        ply("c7", "c5", "c5", "Black attacks the base of White's pawn chain on d4."),
        ply("a2", "a3", "a3", "White forces the pinning bishop to decide."),
        ply("b4", "c3", "Bxc3+", "Black damages White's queenside structure and removes a central defender."),
        ply("b2", "c3", "bxc3", "White accepts doubled pawns in return for the bishop pair and an open b-file."),
        ply("g8", "e7", "Ne7", "Black develops toward f5 and prepares to attack the center."),
      ],
    ),
    line(
      "Classical Variation",
      FRENCH,
      [
        ply("b1", "c3", "Nc3", "White defends e4 with a natural developing move."),
        ply("g8", "f6", "Nf6", "Black increases pressure on e4 and invites an advance."),
        ply("e4", "e5", "e5", "White gains space and drives the knight."),
        ply("f6", "d7", "Nfd7", "The knight retreats toward b6 or f8 while supporting ...c5."),
        ply("f2", "f4", "f4", "White reinforces e5 and builds kingside space."),
        ply("c7", "c5", "c5", "Black attacks d4, the pawn chain's base."),
        ply("g1", "f3", "Nf3", "White develops and reinforces d4."),
        ply("b8", "c6", "Nc6", "Black adds a second attacker to d4."),
      ],
    ),
    line(
      "Rubinstein Variation",
      FRENCH,
      [
        ply("b1", "c3", "Nc3", "White supports e4 and develops."),
        ply("d5", "e4", "dxe4", "Black releases the tension to seek a sound, simplified structure."),
        ply("c3", "e4", "Nxe4", "White recaptures with an active central knight."),
        ply("b8", "d7", "Nd7", "Black develops to challenge the e4 knight without blocking the f-pawn."),
        ply("g1", "f3", "Nf3", "White develops and supports the centralized knight."),
        ply("g8", "f6", "Ngf6", "Black brings the second knight to the central fight."),
        ply("e4", "f6", "Nxf6+", "White exchanges a defender and slightly disrupts Black's coordination."),
        ply("d7", "f6", "Nxf6", "Black recaptures with a developed knight and keeps the pawn structure intact."),
      ],
    ),
    line(
      "MacCutcheon Variation",
      FRENCH,
      [
        ply("b1", "c3", "Nc3", "White defends e4 and develops."),
        ply("g8", "f6", "Nf6", "Black attacks e4 and invites the Classical line."),
        ply("c1", "g5", "Bg5", "White pins the f6 knight to increase control over e4."),
        ply("f8", "b4", "Bb4", "Black counterpins Nc3 instead of passively breaking the first pin."),
        ply("e4", "e5", "e5", "White gains space and attacks the f6 knight."),
        ply("h7", "h6", "h6", "Black attacks the g5 bishop and forces a tactical decision."),
        ply("g5", "d2", "Bd2", "White breaks the c3 pin while preserving the bishop."),
        ply("b4", "c3", "Bxc3", "Black exchanges on c3 to damage the queenside pawns."),
        ply("b2", "c3", "bxc3", "White opens the b-file and keeps a broad pawn center."),
        ply("f6", "e4", "Ne4", "The knight uses the newly weakened central square to become active."),
      ],
    ),
  ],
  "caro-kann": [
    line(
      "Panov Attack",
      CARO,
      [
        ply("e4", "d5", "exd5", "White exchanges to create an isolated-queen's-pawn style center."),
        ply("c6", "d5", "cxd5", "Black recaptures with the c-pawn and opens the c-file."),
        ply("c2", "c4", "c4", "White attacks d5 and accepts a potentially isolated d-pawn for activity."),
        ply("g8", "f6", "Nf6", "Black develops against d5 and e4."),
        ply("b1", "c3", "Nc3", "White adds pressure to d5 and develops naturally."),
        ply("e7", "e6", "e6", "Black reinforces d5 and opens the f8 bishop."),
      ],
    ),
    line(
      "Fantasy Variation",
      CARO,
      [
        ply("f2", "f3", "f3", "White reinforces e4 and prepares a large center, at the cost of king safety."),
        ply("e7", "e6", "e6", "Black supports d5 and prepares to challenge e4."),
        ply("b1", "c3", "Nc3", "White develops and adds another defender to e4."),
        ply("f8", "b4", "Bb4", "Black pins the knight and increases pressure on the center."),
        ply("c1", "f4", "Bf4", "White develops actively before the center closes."),
        ply("b8", "d7", "Nd7", "Black develops and prepares ...e5 or ...Ngf6."),
      ],
    ),
    line(
      "Two Knights Variation",
      [
        ply("e2", "e4", "e4", "White takes the center."),
        ply("c7", "c6", "c6", "Black prepares a supported ...d5."),
        ply("b1", "c3", "Nc3", "White develops while keeping the d-pawn flexible."),
        ply("d7", "d5", "d5", "Black challenges e4."),
        ply("g1", "f3", "Nf3", "White develops a second knight and increases central pressure."),
        ply("c8", "g4", "Bg4", "Black develops outside the pawn chain and pins the f3 knight."),
        ply("h2", "h3", "h3", "White asks the bishop to clarify the pin."),
        ply("g4", "f3", "Bxf3", "Black exchanges the knight to reduce White's central control."),
        ply("d1", "f3", "Qxf3", "White recaptures while placing the queen actively against d5 and f7."),
        ply("e7", "e6", "e6", "Black stabilizes d5 and opens the f8 bishop."),
      ],
    ),
    line(
      "Bronstein–Larsen Variation",
      CARO,
      [
        ply("b1", "c3", "Nc3", "White protects e4 and develops."),
        ply("d5", "e4", "dxe4", "Black exchanges before White can advance e5."),
        ply("c3", "e4", "Nxe4", "White recaptures with central piece activity."),
        ply("g8", "f6", "Nf6", "Black attacks the e4 knight and develops."),
        ply("e4", "f6", "Nxf6+", "White doubles Black's f-pawns in return for giving up the active knight."),
        ply("g7", "f6", "gxf6", "Black accepts the structural weakness to gain an open g-file and the bishop pair."),
        ply("g1", "f3", "Nf3", "White develops toward the weakened kingside."),
        ply("c8", "f5", "Bf5", "Black activates the light bishop before playing ...e6."),
      ],
    ),
  ],
  scotch: [
    line(
      "Scotch Gambit",
      SCOTCH,
      [
        ply("f1", "c4", "Bc4", "White leaves the d4 pawn temporarily to gain development and pressure on f7."),
        ply("f8", "c5", "Bc5", "Black develops actively and meets the attack with counterpressure."),
        ply("c2", "c3", "c3", "White offers another pawn to build a broad center with tempo."),
        ply("g8", "f6", "Nf6", "Black develops and attacks e4 rather than collecting material blindly."),
        ply("c3", "d4", "cxd4", "White recaptures and restores a strong central pawn."),
        ply("c5", "b4", "Bb4+", "Black develops with check and interferes with castling."),
      ],
    ),
    line(
      "Mieses Variation",
      SCOTCH,
      [
        ply("f3", "d4", "Nxd4", "White restores material with a centralized knight."),
        ply("g8", "f6", "Nf6", "Black develops and attacks e4."),
        ply("d4", "c6", "Nxc6", "White removes the defender and changes Black's queenside structure."),
        ply("b7", "c6", "bxc6", "Black recaptures toward the center and opens the b-file."),
        ply("e4", "e5", "e5", "White gains space and drives the f6 knight."),
        ply("d8", "e7", "Qe7", "Black pins the e-pawn against the king and prepares ...Nd5."),
        ply("d1", "e2", "Qe2", "White breaks the pin and reinforces e5."),
        ply("f6", "d5", "Nd5", "Black centralizes the knight and attacks c3 and e3."),
      ],
    ),
    line(
      "Steinitz Variation",
      SCOTCH,
      [
        ply("f3", "d4", "Nxd4", "White recaptures the central pawn."),
        ply("d8", "h4", "Qh4", "Black attacks e4 and d4 at once, accepting early queen exposure."),
        ply("b1", "c3", "Nc3", "White develops and adds protection to d5 and e4."),
        ply("f8", "b4", "Bb4", "Black pins the c3 knight and increases pressure on e4."),
        ply("f1", "e2", "Be2", "White prepares castling and attacks the queen's possible retreat squares."),
        ply("h4", "e4", "Qxe4", "Black wins the e4 pawn while White's king remains in the center."),
        ply("d4", "b5", "Ndb5", "White creates threats on c7 and d6 to compensate for the pawn."),
        ply("b4", "c3", "Bxc3+", "Black removes the second knight with check and simplifies the attack."),
      ],
    ),
    line(
      "Göring Gambit",
      SCOTCH,
      [
        ply("c2", "c3", "c3", "White offers a second pawn to accelerate development and open central files."),
        ply("d4", "c3", "dxc3", "Black accepts and moves the extra pawn closer to promotion, but loses more time."),
        ply("b1", "c3", "Nxc3", "White recaptures with development and obtains open diagonals."),
        ply("f8", "b4", "Bb4", "Black pins the knight and develops with pressure."),
        ply("f1", "c4", "Bc4", "White brings another piece toward f7 and prepares castling."),
        ply("d7", "d6", "d6", "Black supports e5 and gives the c8 bishop a route."),
      ],
    ),
  ],
  "queens-gambit": [
    line(
      "Tarrasch Defense",
      QUEENS_GAMBIT,
      [
        ply("e7", "e6", "e6", "Black supports d5 and opens the f8 bishop."),
        ply("b1", "c3", "Nc3", "White increases pressure on d5."),
        ply("c7", "c5", "c5", "Black immediately challenges White's center and accepts a possible isolated d-pawn."),
        ply("c4", "d5", "cxd5", "White clarifies the center before Black can advance."),
        ply("e6", "d5", "exd5", "Black recaptures with the e-pawn, creating an isolated queen's pawn but open piece lines."),
        ply("g1", "f3", "Nf3", "White develops and prepares to blockade d4 or pressure d5."),
        ply("b8", "c6", "Nc6", "Black develops behind the active isolated pawn and supports d4 ideas."),
      ],
    ),
    line(
      "Semi-Slav Defense",
      QUEENS_GAMBIT,
      [
        ply("e7", "e6", "e6", "Black supports d5 and keeps options between QGD and Semi-Slav."),
        ply("b1", "c3", "Nc3", "White develops another attacker on d5."),
        ply("g8", "f6", "Nf6", "Black reinforces d5 and controls e4."),
        ply("g1", "f3", "Nf3", "White supports d4 and prepares e3."),
        ply("c7", "c6", "c6", "Black builds the triangle that makes d5 exceptionally solid."),
        ply("e2", "e3", "e3", "White completes the central support and opens the f1 bishop."),
        ply("b8", "d7", "Nbd7", "Black prepares ...Bd6, ...e5, or a central capture on c4."),
      ],
    ),
    line(
      "Cambridge Springs Defense",
      QUEENS_GAMBIT,
      [
        ply("e7", "e6", "e6", "Black supports the center and opens the f8 bishop."),
        ply("b1", "c3", "Nc3", "White adds pressure to d5."),
        ply("g8", "f6", "Nf6", "Black develops and reinforces d5."),
        ply("c1", "g5", "Bg5", "White pins the f6 knight and increases central pressure."),
        ply("b8", "d7", "Nbd7", "Black develops while protecting f6 with the queen."),
        ply("e2", "e3", "e3", "White opens the light bishop and supports d4."),
        ply("c7", "c6", "c6", "Black strengthens d5 and prepares the queen sortie."),
        ply("g1", "f3", "Nf3", "White completes natural development."),
        ply("d8", "a5", "Qa5", "Black pins c3, attacks a2, and creates tactical pressure on g5."),
      ],
    ),
    line(
      "Albin Countergambit",
      QUEENS_GAMBIT,
      [
        ply("e7", "e5", "e5", "Black counteroffers a central pawn to gain space and rapid activity."),
        ply("d4", "e5", "dxe5", "White accepts the pawn and leaves d4 vacant."),
        ply("d5", "d4", "d4", "Black advances with tempo, cramping White and restricting Nc3."),
        ply("g1", "f3", "Nf3", "White attacks d4 and develops toward castling."),
        ply("b8", "c6", "Nc6", "Black develops with another attacker on e5 and d4."),
        ply("g2", "g3", "g3", "White prepares Bg2 to blockade and attack d5."),
        ply("c8", "e6", "Be6", "Black develops actively and supports queenside castling ideas."),
      ],
    ),
  ],
  slav: [
    line(
      "Geller Gambit",
      SLAV,
      [
        ply("b1", "c3", "Nc3", "White adds pressure to d5 and prepares e4."),
        ply("g8", "f6", "Nf6", "Black reinforces d5 and develops."),
        ply("g1", "f3", "Nf3", "White supports d4 and prepares central expansion."),
        ply("d5", "c4", "dxc4", "Black captures c4 before White can play e3."),
        ply("e2", "e4", "e4", "White sacrifices the c-pawn temporarily to seize the full center."),
        ply("b7", "b5", "b5", "Black tries to hold the extra pawn with queenside space."),
        ply("e4", "e5", "e5", "White drives the f6 knight and gains attacking time."),
        ply("f6", "d5", "Nd5", "The knight centralizes and blocks the d-file."),
        ply("a2", "a4", "a4", "White undermines the b5 pawn chain and prepares to recover c4."),
        ply("e7", "e6", "e6", "Black stabilizes the center and opens the f8 bishop."),
      ],
    ),
    line(
      "Chebanenko Slav",
      SLAV,
      [
        ply("g1", "f3", "Nf3", "White develops and supports d4."),
        ply("g8", "f6", "Nf6", "Black reinforces d5."),
        ply("b1", "c3", "Nc3", "White increases pressure on d5."),
        ply("a7", "a6", "a6", "Black prepares ...b5 while keeping the light bishop free."),
        ply("c4", "c5", "c5", "White gains queenside space and restricts ...c5."),
        ply("c8", "f5", "Bf5", "Black develops the bishop outside the pawn chain."),
        ply("c1", "f4", "Bf4", "White mirrors the active bishop development and supports e5."),
        ply("b8", "d7", "Nbd7", "Black prepares ...e5 and supports c5."),
      ],
    ),
    line(
      "Semi-Slav Triangle",
      SLAV,
      [
        ply("g1", "f3", "Nf3", "White develops and reinforces d4."),
        ply("g8", "f6", "Nf6", "Black develops with central control."),
        ply("b1", "c3", "Nc3", "White adds pressure to d5."),
        ply("e7", "e6", "e6", "Black locks the light bishop temporarily to make d5 extremely solid."),
        ply("e2", "e3", "e3", "White opens the f1 bishop and completes the center."),
        ply("b8", "d7", "Nbd7", "Black prepares ...Bd6 and the freeing ...e5 break."),
        ply("f1", "d3", "Bd3", "White develops toward h7 and supports e4."),
        ply("d5", "c4", "dxc4", "Black waits until development is ready before taking the c4 pawn."),
      ],
    ),
    line(
      "Schlechter Slav",
      SLAV,
      [
        ply("g1", "f3", "Nf3", "White develops and supports d4."),
        ply("g8", "f6", "Nf6", "Black reinforces d5."),
        ply("b1", "c3", "Nc3", "White increases central pressure."),
        ply("g7", "g6", "g6", "Black prepares a fianchetto that keeps the c8 bishop flexible."),
        ply("c4", "d5", "cxd5", "White clarifies the center before Black develops Bg7."),
        ply("c6", "d5", "cxd5", "Black recaptures and opens the c-file."),
        ply("c1", "f4", "Bf4", "White develops actively and targets c7."),
        ply("f8", "g7", "Bg7", "Black completes the fianchetto and pressure on d4."),
      ],
    ),
  ],
  "kings-indian": [
    line(
      "Four Pawns Attack",
      KID,
      [
        ply("e2", "e4", "e4", "White occupies the full center and supports d5."),
        ply("d7", "d6", "d6", "Black restrains e5 and prepares castling."),
        ply("f2", "f4", "f4", "White builds maximum space and prepares e5."),
        ply("e8", "g8", "O-O", "Black secures the king before attacking the center."),
        ply("g1", "f3", "Nf3", "White develops behind the pawn wall and supports e5."),
        ply("c7", "c5", "c5", "Black attacks d4 before the huge center can advance safely."),
      ],
    ),
    line(
      "Averbakh Variation",
      KID,
      [
        ply("e2", "e4", "e4", "White creates the classical pawn center."),
        ply("d7", "d6", "d6", "Black controls e5 and prepares castling."),
        ply("f1", "e2", "Be2", "White develops calmly and prepares king safety."),
        ply("e8", "g8", "O-O", "Black completes the fianchetto setup."),
        ply("c1", "g5", "Bg5", "White restrains ...e5 by pinning the f6 knight."),
        ply("c7", "c5", "c5", "Black switches to queenside pressure against d4."),
      ],
    ),
    line(
      "Petrosian Variation",
      KID,
      [
        ply("e2", "e4", "e4", "White establishes the broad center."),
        ply("d7", "d6", "d6", "Black prepares castling and controls e5."),
        ply("g1", "f3", "Nf3", "White develops and reinforces d4."),
        ply("e8", "g8", "O-O", "Black secures the king."),
        ply("f1", "e2", "Be2", "White prepares castling without committing the f-pawn."),
        ply("e7", "e5", "e5", "Black challenges the center and invites d5."),
        ply("d4", "d5", "d5", "White closes the center and gains queenside space."),
        ply("a7", "a5", "a5", "Black slows b4 and creates a queenside foothold before attacking on the kingside."),
      ],
    ),
    line(
      "Makogonov Variation",
      KID,
      [
        ply("e2", "e4", "e4", "White builds the full pawn center."),
        ply("d7", "d6", "d6", "Black supports the hypermodern setup."),
        ply("h2", "h3", "h3", "White prevents ...Ng4 and prepares g4 without committing the f-pawn."),
        ply("e8", "g8", "O-O", "Black castles before opening the center."),
        ply("g1", "f3", "Nf3", "White develops and supports d4."),
        ply("e7", "e5", "e5", "Black challenges the center directly."),
        ply("d4", "d5", "d5", "White closes the center and gains space."),
        ply("b8", "a6", "Na6", "Black heads for c5, where the knight can pressure d3 and b3."),
      ],
    ),
  ],
  english: [
    line(
      "Four Knights Variation",
      ENGLISH,
      [
        ply("e7", "e5", "e5", "Black occupies the center and creates a reversed Sicilian."),
        ply("b1", "c3", "Nc3", "White develops and strengthens d5."),
        ply("g8", "f6", "Nf6", "Black develops against e4 and d5."),
        ply("g1", "f3", "Nf3", "White pressures e5 and completes the four-knights framework."),
        ply("b8", "c6", "Nc6", "Black supports e5 and controls d4."),
        ply("g2", "g3", "g3", "White prepares the characteristic kingside fianchetto."),
        ply("f8", "b4", "Bb4", "Black pins Nc3 and makes d4 harder to arrange."),
        ply("f1", "g2", "Bg2", "White completes the long-diagonal development."),
        ply("e8", "g8", "O-O", "Black secures the king before central expansion."),
      ],
    ),
    line(
      "Mikenas–Carls Variation",
      ENGLISH,
      [
        ply("g8", "f6", "Nf6", "Black controls e4 while staying flexible."),
        ply("b1", "c3", "Nc3", "White reinforces d5 and prepares e4."),
        ply("e7", "e6", "e6", "Black opens the f8 bishop and prepares ...d5."),
        ply("e2", "e4", "e4", "White builds a Botvinnik-style center in one move."),
        ply("d7", "d5", "d5", "Black attacks the new center before it is fully supported."),
        ply("e4", "e5", "e5", "White gains space and drives the f6 knight."),
        ply("d5", "d4", "d4", "Black advances with tempo on the c3 knight."),
        ply("e5", "f6", "exf6", "White removes the knight and disturbs Black's kingside pawn structure."),
        ply("d4", "c3", "dxc3", "Black captures the c3 knight and creates a dangerous passed pawn."),
        ply("b2", "c3", "bxc3", "White eliminates the passer and opens the b-file."),
      ],
    ),
    line(
      "Bremen System",
      ENGLISH,
      [
        ply("e7", "e5", "e5", "Black takes central space."),
        ply("b1", "c3", "Nc3", "White controls d5 and develops."),
        ply("g8", "f6", "Nf6", "Black reinforces e4 and d5."),
        ply("g2", "g3", "g3", "White prepares the fianchetto."),
        ply("d7", "d5", "d5", "Black occupies the center before White can prevent it."),
        ply("c4", "d5", "cxd5", "White exchanges to keep Black from maintaining both central pawns."),
        ply("f6", "d5", "Nxd5", "Black recaptures with an active knight."),
        ply("f1", "g2", "Bg2", "White develops with pressure on d5."),
        ply("d5", "b6", "Nb6", "The knight retreats from the bishop's attack while controlling c4."),
      ],
    ),
    line(
      "Anglo-Scandinavian Defense",
      ENGLISH,
      [
        ply("d7", "d5", "d5", "Black challenges c4 immediately and opens the c8 bishop."),
        ply("c4", "d5", "cxd5", "White accepts the central exchange."),
        ply("d8", "d5", "Qxd5", "Black recaptures with the queen, accepting a developing tempo."),
        ply("b1", "c3", "Nc3", "White develops while attacking the queen."),
        ply("d5", "d8", "Qd8", "Black retreats safely and accepts a modest loss of time."),
        ply("d2", "d4", "d4", "White uses the tempo to establish central space."),
        ply("g8", "f6", "Nf6", "Black develops and attacks e4."),
        ply("g1", "f3", "Nf3", "White reinforces the center and prepares castling."),
      ],
    ),
    line(
      "Hedgehog Setup",
      ENGLISH,
      [
        ply("c7", "c5", "c5", "Black mirrors White and keeps the structure flexible."),
        ply("g1", "f3", "Nf3", "White develops and controls d4 and e5."),
        ply("g8", "f6", "Nf6", "Black mirrors the central control."),
        ply("g2", "g3", "g3", "White prepares the kingside fianchetto."),
        ply("b7", "b6", "b6", "Black prepares ...Bb7 and a compact queenside shell."),
        ply("f1", "g2", "Bg2", "White activates the long diagonal."),
        ply("c8", "b7", "Bb7", "Black develops against g2 and e4."),
        ply("e1", "g1", "O-O", "White secures the king before expanding."),
        ply("e7", "e6", "e6", "Black completes the Hedgehog pawn shell and prepares ...Be7."),
      ],
    ),
  ],
};
